equinor/fmu-dataio

src/fmu/dataio/dataio.py, tests/test_fmu_dataio_case.py
Ref #19 
Outgoing metadata for case must contain `access.asset`.
=> Case access field

src/fmu/dataio/_export_item.py
=> Upgrade valid contents

src/fmu/dataio/_export_item.py
Including `regions` in valid content
=> Allow regions as content

src/fmu/dataio/_export_item.py, src/fmu/dataio/_utils.py, src/fmu/dataio/dataio.py, tests/test_fmu_dataio_surface.py
Attempting a solution for #60 - exporting to subfolder.
Code will allow it, but issue a warning.
Have not tested edge-cases etc yet, and I also want to test it live. But have a look at the suggested concepts for doing this.
=> Export subfolder

src/fmu/dataio/_export_item.py, src/fmu/dataio/dataio.py, tests/test_export_item.py, tests/test_fmu_dataio_surface.py
Attempt to establish the `display` block and get a feel for how & where it should/could fit in.
For now only setting the `display.name`.
WIP pending discussions
=> WIP: Establish visual settings

src/fmu/dataio/_utils.py, tests/test_fmu_dataio_generic.py, tests/test_fmu_dataio_utils.py
=> WIP: filename with dots

src/fmu/dataio/_export_item.py
Adding subcrop as valid content
=> add_subcrop

src/fmu/dataio/_export_item.py
=> Add kxh as valid content

README.md
=> Iterate on readme

requirements/requirements.txt, src/fmu/dataio/_export_item.py, tests/test_fmu_dataio_table.py
Adding support for pyarrow tables and the smry content
=> Pyarrow table

src/fmu/dataio/_export_item.py, src/fmu/dataio/dataio.py, tests/test_fmu_dataio_generic.py
Add support for Points. Note that extra columns (Poinst attributes) are listed as spec:attributes:
```
data:
stratigraphic: false
name: test2
content: depth
vertical_domain: depth
depth_reference: msl
is_prediction: true
is_observation: false
spec:
attributes:                                      <<<<
- A1
- A2
bbox:
```
=> Add support for Points

tests/test_fmu_dataio_points.py
Forgot to add test file in #122
=> Add tests for points

src/fmu/dataio/_export_item.py, src/fmu/dataio/dataio.py, tests/test_fmu_dataio_generic.py
=> Workflow reference

src/fmu/dataio/_export_item.py, src/fmu/dataio/dataio.py
=> Grammar and remove some redundant text

src/fmu/dataio/dataio.py, tests/test_fmu_dataio_generic.py
Solve #48 and refactor a little bit
=> use the access_ssdl input argument

src/fmu/dataio/dataio.py, tests/test_fmu_dataio_case.py, tests/test_fmu_dataio_cube.py, tests/test_fmu_dataio_generic.py, tests/test_fmu_dataio_grids.py, tests/test_fmu_dataio_points.py, tests/test_fmu_dataio_polygons.py, tests/test_fmu_dataio_surface.py, tests/test_fmu_dataio_table.py, tests/test_fmu_dataio_utils.py
Require that config is provided, and that it contains specific keys. The list of specific keys used here are collected based on usage in existing code.
=> Require config

src/fmu/dataio/_export_item.py, src/fmu/dataio/_utils.py, tests/test_export_item.py, tests/test_fmu_dataio_utils.py
Originally mean to solve #105 but as far as I can see, it has been solved already. However, did some small refactoring etc. Creating draft PR for discussions.
=> Display name

schema/definitions/0.8.0/examples/surface_fluid_contact.yml, schema/definitions/0.8.0/schema/fmu_results.json, tests/test_schema.py
=> fluid contact

tests/test_export_item.py
=> test display name for more datatypes

tests/test_fmu_dataio_generic.py
=> add missing yaml backread

src/fmu/dataio/_export_item.py, tests/test_export_item.py, tests/test_fmu_dataio_generic.py
=> Description as strings

src/fmu/dataio/dataio.py, tests/test_fmu_dataio_surface.py
This may be regarded as a tmp fix as long as the SUMO registration is in development. With this fix, it should be possible to run the RMS forward jobs that use fmu-dataio in ERT without the hook workflows that initializes the case and/or uploads to SUMO.
=> Allow ERT run (with warning) with missing case metadata

requirements/requirements.txt, tests/test_export_item.py, tests/test_fmu_dataio_cube.py, tests/test_fmu_dataio_generic.py, tests/test_fmu_dataio_grids.py, tests/test_fmu_dataio_points.py, tests/test_fmu_dataio_polygons.py, tests/test_fmu_dataio_utils.py
=> Align to xtgeo latest

schema/definitions/0.8.0/schema/fmu_results.json
=> add spec.npolys

examples/s/d/nn/xcase/realization-0/iter-0/rms/bin/export_faultpolygons.py, src/fmu/dataio/_export_item.py, src/fmu/dataio/dataio.py, tests/test_fmu_dataio_points.py, tests/test_fmu_dataio_polygons.py
=> Allow "csv|xtgeo" format for Points/Polygons

src/fmu/dataio/__init__.py
=> Removing modification of root logger as it creates unforseen consequences

docs/conf.py, docs/datamodel.rst, docs/index.rst, docs/overview.rst
Add documentation of the data model to the fmu-dataio docs.
=> Metadata docs

tests/test_schema/test_schema_logic.py
Migrating and adapting the schema tests from legacy tests.
=> Migrate schema tests

requirements/requirements_test.txt, src/fmu/dataio/_filedata_provider.py, src/fmu/dataio/_fmu_provider.py, src/fmu/dataio/_metadata.py, src/fmu/dataio/_objectdata_provider.py, src/fmu/dataio/_utils.py, src/fmu/dataio/dataio.py, src/fmu/dataio/hook_implementations/jobs.py, src/fmu/dataio/scripts/create_case_metadata.py, src/fmu/dataio/testc.py, tests/data/drogon/ertrun1/share/metadata/fmu_case.yml, tests/test_units/conftest.py, tests/test_units/test_dataio.py, tests/test_units/test_ert2_context.py, tests/test_units/test_filedataprovider_class.py, tests/test_units/test_fmuprovider_class.py, tests/test_units/test_initialize_case.py, tests/test_units/test_metadata_class.py, tests/test_units/test_objectdataprovider_class.py, tests/test_units/test_rms_context.py
Merely fixes from testing in Drogon. Also added stuff that make Komodo bleeding fail.
=> Fixes part1

docs/examples.rst, docs/index.rst, docs/overview.rst
Adding a section to the docs explaining how to get started and how to set up FMU workflow to use fmu-dataio. This section is referenced from the Sumo documentation.
=> Docs for getting started

src/fmu/dataio/_filedata_provider.py, tests/test_units/test_filedataprovider_class.py
=> create filenames with single double underscores

src/fmu/dataio/_fmu_provider.py, src/fmu/dataio/dataio.py, tests/test_units/test_fmuprovider_class.py
=> Allow workflow argument to be a dict

docs/examples.rst, schema/definitions/0.8.0/examples/surface_depth.yml, schema/definitions/0.8.0/schema/fmu_results.json, src/fmu/dataio/_objectdata_provider.py, src/fmu/dataio/dataio.py, tests/test_units/test_metadata_class.py
=> Add NaN flag

src/fmu/dataio/_utils.py, tests/test_units/test_utils.py
Establish a test module for the utils module, and add 1 test. Also add handling of `None` to utils.check_if_number()
=> check_if_number util function handles None, and add test

src/fmu/dataio/_objectdata_provider.py, src/fmu/dataio/dataio.py, tests/test_units/test_dataio.py, tests/test_units/test_metadata_class.py
=> Handle content when given as dict

src/fmu/dataio/dataio.py
This PR is solving issue #252 in which the users get error message when trying to use AggregatedData class to create aggregated metadata for object type table
=> Fix issue with aggregated table

README.md
Added some text after testing myself  with pytest with some help from Per Olav
=> Readme edit for local testing

.github/workflows/ci-fmudataio.yml, schema/definitions/0.8.0/schema/fmu_results.json, tests/test_schema/test_schema_logic.py
=> Require data.top and data.base or none

schema/definitions/0.8.0/examples/surface_seismic_amplitude.yml, schema/definitions/0.8.0/schema/fmu_results.json, src/fmu/dataio/_definitions.py, src/fmu/dataio/dataio.py, tests/test_units/test_dataio.py
=> rename seismic.offset to seismic.stacking_offset

schema/definitions/0.8.0/examples/surface_seismic_amplitude.yml, schema/definitions/0.8.0/schema/fmu_results.json, src/fmu/dataio/_definitions.py, tests/test_units/test_dataio.py
This may solve  #289 (but a slightly different solution than originally proposed)
=> Add 'calculation' as field for content 'seismic'

schema/definitions/0.8.0/examples/aggregated_surface_depth.yml, schema/definitions/0.8.0/examples/case.yml, schema/definitions/0.8.0/examples/polygons_field_outline.yml, schema/definitions/0.8.0/examples/preprocessed_surface_depth.yml, schema/definitions/0.8.0/examples/surface_depth.yml, schema/definitions/0.8.0/examples/surface_fluid_contact.yml, schema/definitions/0.8.0/examples/surface_seismic_amplitude.yml, schema/definitions/0.8.0/examples/table_inplace.yml, schema/definitions/0.8.0/schema/fmu_results.json
Add fmu.context to the schema, and make fmu.context.stage contractual.
Links to #293
=> add fmu.context.stage to schema and examples

schema/definitions/0.8.0/schema/fmu_results.json
Add `data.time` to `$contractual` so it's searchable in Sumo
=> Make data.time contractual

schema/definitions/0.8.0/schema/fmu_results.json
=> make -1 and 1 valid values for data.spec.yflip

README.md
* Removed examples, replaced with link to documentation.
* Added badge for docs build status.
=> Brush-up the README

.github/workflows/ci-fmudataio.yml, src/fmu/dataio/_filedata_provider.py
=> test py37, 38, 39, 310 and 311

docs/datamodel.rst, src/fmu/dataio/dataio.py, src/fmu/dataio/scripts/create_case_metadata.py, tests/data/drogon/ertrun1/share/metadata/fmu_case.yml, tests/test_units/test_initialize_case.py
Set restart_from as deprecated in InitializeCase class and update the documentation
=> Clean-up related to restart_from

schema/definitions/0.8.0/examples/table_wellpicks.yml, src/fmu/dataio/_definitions.py, tests/conftest.py, tests/test_units/test_table.py
This PR partly solves #341 and adds the content `wellpicks`.
- Add wellpicks to list of known contents
- Add definitions of known table index columns
=> Add wellpicks to known contents

.github/workflows/fmudataio-documention.yml
Sphinx changes the path which make our github action fail.
=> Update path due to sphinx changes

src/fmu/dataio/_definitions.py, src/fmu/dataio/_objectdata_provider.py, src/fmu/dataio/_utils.py, src/fmu/dataio/dataio.py, tests/test_units/test_dictionary.py
Suggested solution to issue #354
=> Include dict

src/fmu/dataio/_objectdata_provider.py, src/fmu/dataio/_utils.py
Running _pytest_ gives 49 warnings. This PR cleans it up.
Ninja trick: Run pytest as: `python -W error -m pytest -q` this promotes warnings to exceptions inc. trackbacks. This makes it super easy to find where you need to update your code.
```python
pytest -q               
============================================================================================= test session starts ==============================================================================================
platform darwin -- Python 3.10.13, pytest-7.4.4, pluggy-1.3.0
rootdir: /Users/JLOV/src/fmu-dataio
configfile: pyproject.toml
testpaths: tests
plugins: cov-4.1.0, mock-3.12.0, hypothesis-6.92.4
collected 210 items …
```
=> CLN: Replace .dataframe with .get_dataframe()

docs/conf.py, docs/datastructure.rst, docs/gen-datastructure.py, docs/index.rst, pyproject.toml
#423 
Testing of building sphinx docs from  pydantic
=> DOC: Build datastructure documentation

src/fmu/dataio/datastructure/configuration/global_configuration.py, tests/test_units/test_dataio.py
https://github.com/equinor/fmu-dataio/pull/422#discussion_r1470623136
=> API: Use UserWarning insted of PendingDeprecationWarning

src/fmu/dataio/_metadata.py, src/fmu/dataio/datastructure/meta/meta.py
https://github.com/equinor/fmu-dataio/blob/26535ff268a478e5b6f2a49f6de9ee8a6257ebd6/schema/definitions/0.8.0/schema/fmu_results.json#L158-179
=> BUG: Add System information to Tracklog event

pyproject.toml, tests/conftest.py
Cant find this being used anywhere. Removing.
=> CLN: Remove termcolor dependency

.github/workflows/ci-fmudataio.yml
Resolves https://github.com/equinor/fmu-dataio/issues/449
=> TSN: Nighyly CI

src/fmu/dataio/_metadata.py, tests/test_units/test_metadata_class.py
Addresses: https://github.com/equinor/fmu-dataio/issues/457
=> CLN: Construct tracklog using pydantic

schema/definitions/0.8.0/schema/fmu_meta.json, schema/definitions/0.8.0/schema/fmu_results.json, src/fmu/dataio/datastructure/meta/content.py, src/fmu/dataio/datastructure/meta/enums.py
Resolves: https://github.com/equinor/fmu-dataio/issues/464
=> ENH: Add facies_thickness as content type

schema/definitions/0.8.0/schema/fmu_results.json, src/fmu/dataio/_objectdata_provider.py, src/fmu/dataio/datastructure/meta/specification.py
Addresses: https://github.com/equinor/fmu-dataio/issues/457
For future ref.: https://equinor.slack.com/archives/C06E3UTGTEV/p1707511982786159
=> CLN: Construct Spec using pydantic

src/fmu/dataio/_objectdata_provider.py
Addresses: https://github.com/equinor/fmu-dataio/issues/457
=> CLN: Refactor and type-Annotate time data functions

src/fmu/dataio/_objectdata_provider.py, tests/test_units/test_objectdataprovider_class.py, tests/test_units/test_table.py
Adressess: https://github.com/equinor/fmu-dataio/issues/457
Merge after: https://github.com/equinor/fmu-dataio/pull/468
=> CLN: Add derived object descriptor dataclass

src/fmu/dataio/_definitions.py, src/fmu/dataio/_objectdata_provider.py, src/fmu/dataio/dataio.py, src/fmu/dataio/datastructure/export/content.py, tests/test_schema/test_pydantic_logic.py
Resolves: https://github.com/equinor/fmu-dataio/issues/474
=> CLN: Convert AllowContents dict to Pydantic

tests/test_units/test_dataio.py
Deactivated by mistake during PR: https://github.com/equinor/fmu-dataio/pull/443
=> TST: Enable test_norwegian_letters_globalconfig_as_json

docs/overview.rst, docs/preparations.rst
Use the same header style on similar headers. Some minor fixups in addition.
=> DOC: Header alignment and fixups

docs/datamodel.rst
Solve fundamental part of #487, however much more discussion to be had on this topic.
=> DOC: Document how checksum is made

src/fmu/dataio/dataio.py
Solves: https://github.com/equinor/fmu-dataio/issues/498
=> CLN: Refactor generate_aggr_uuid

src/fmu/dataio/_objectdata_provider.py, src/fmu/dataio/dataio.py, src/fmu/dataio/datastructure/_internal/content.py, tests/test_schema/test_pydantic_logic.py
=> CLN: Rename datastructure.export to datastructure._internal

src/fmu/dataio/_metadata.py, src/fmu/dataio/_objectdata_provider.py, src/fmu/dataio/dataio.py, src/fmu/dataio/datastructure/_internal/__init__.py, src/fmu/dataio/datastructure/_internal/internal.py, tests/test_schema/test_pydantic_logic.py
Addresses: [#457](https://github.com/equinor/fmu-dataio/issues/457)
=> CLN: InitializeCase object with json schema

schema/definitions/0.8.0/schema/fmu_meta.json, src/fmu/dataio/datastructure/meta/meta.py
Extends: #423 
Set schema field according to: https://docs.pydantic.dev/latest/concepts/json_schema/
=> BUG: Set correct schema version

schema/definitions/0.8.0/schema/fmu_meta.json, src/fmu/dataio/datastructure/meta/meta.py
Solves https://github.com/equinor/fmu-dataio/issues/511
=> BUG: Add relative/absolute_path_symlink to File model

src/fmu/dataio/case.py, src/fmu/dataio/dataio.py
This PR is part of a ab effort to refactor dataio.py to improve code manageability and readability. In this phase, we're focusing on extracting the InitializeCase class into its own module.
=> CLN: Move InitializeCase to own file

schema/definitions/0.8.0/schema/fmu_meta.json, src/fmu/dataio/_objectdata_provider.py, src/fmu/dataio/datastructure/meta/content.py, src/fmu/dataio/datastructure/meta/meta.py, tools/sumo-explorer-validate.py
Ive got access to Sverdup and have done a run using the `sumo-explorer-validate.py` script i found these errors in the pydantic model.
=> BUG: 2D/3D BoundingBox2D, mark iter.id Optional

tools/sumo-explorer-validate.py
Imp. sumo explorer validater. Major speed up.
```python
python3 tools/sumo-explorer-validate.py
1.00     FMUClassEnum.case              None                           Troll
1.00     FMUClassEnum.case              None                           Drogon
27.0     FMUClassEnum.case              None                           Johan Sverdrup
234      FMUClassEnum.table             ContentEnum.relperm            Drogon
246      FMUClassEnum.dictionary        ContentEnum.parameters         Drogon
250      FMUClassEnum.table             ContentEnum.rft                Drogon
546      FMUClassEnum.table             ContentEnum.relperm            Troll
581      FMUClassEnum.table             ContentEnum.pvt                Troll
595      FMUClassEnum.dictionary        ContentEnum.parameters …
```
=> TST: Imp. sumo explorer validater perf.

src/fmu/dataio/_metadata.py, src/fmu/dataio/providers/_filedata.py, tests/test_units/test_filedataprovider_class.py
PR that closes #569, and is a step towards the https://github.com/equinor/fmu-dataio/issues/457
=> CLN: Use pydantic for filedata

src/fmu/dataio/providers/objectdata/_base.py, src/fmu/dataio/providers/objectdata/_provider.py, src/fmu/dataio/providers/objectdata/_tables.py, src/fmu/dataio/providers/objectdata/_xtgeo.py
=> CLN: Adjust ObjectDataProvider typing

schema/definitions/0.8.0/schema/fmu_meta.json, src/fmu/dataio/_utils.py, src/fmu/dataio/datastructure/meta/content.py, src/fmu/dataio/providers/objectdata/_base.py, tests/test_units/test_objectdataprovider_class.py, tests/test_units/test_utils.py
=> FIX: Make `FMUDateTime.value` a proper datetime

src/fmu/dataio/dataio.py
Forgot a save on the `faultroom-format` PR... , so here is small patch with additional changes
=> FIX: additional patch on fault room format

src/fmu/dataio/_definitions.py, src/fmu/dataio/dataio.py, src/fmu/dataio/datastructure/_internal/internal.py, tests/test_units/test_enum_classes.py
PR to update FmuContext values to lowercase member names for simplification (in e.g. type checking)
=> CLN: Update FmuContext values to lowercase member names

pyproject.toml
Temporary measure until we fix what has been broken.
=> BLD: pin pydantic < 2.7.0

src/fmu/dataio/_utils.py, src/fmu/dataio/dataio.py
=>  CLN: Deprecate table_include_index

src/fmu/dataio/dataio.py, src/fmu/dataio/providers/_fmu.py, tests/test_units/test_fmuprovider_class.py
The realization argument to dataio is not implemented anywhere. 
Closes #612
=> CLN: Deprecate unused realization argument

src/fmu/dataio/_definitions.py, src/fmu/dataio/dataio.py, src/fmu/dataio/providers/_filedata.py, tests/test_units/test_enum_classes.py, tests/test_units/test_filedataprovider_class.py, tests/test_units/test_prerealization_surfaces.py, tests/test_units/test_rms_context.py
=> CLN: Drop support for fmu_context='case_symlink_realization'

src/fmu/dataio/dataio.py
Add warning with link to 'Getting started' if invalid config file.
=> ENH: Add UserWarning with 'Getting started' link

src/fmu/dataio/dataio.py, src/fmu/dataio/providers/_filedata.py, src/fmu/dataio/providers/objectdata/_base.py, tests/test_units/test_dataio.py, tests/test_units/test_ert_context.py, tests/test_units/test_prerealization_surfaces.py
=> DEP: Stop support for absolute paths in 'forcefolder'

schema/definitions/0.8.0/schema/fmu_meta.json, src/fmu/dataio/datastructure/meta/content.py, tests/test_units/test_metadata_class.py
=> FIX: Switch order of bbox types

src/fmu/dataio/_definitions.py, src/fmu/dataio/_utils.py, src/fmu/dataio/dataio.py, tests/test_units/test_ert_context.py, tests/test_units/test_rms_context.py
Solving issue https://github.com/equinor/fmu-dataio/issues/495
Revival of pull #496
=> API: Export pyarrow as parquet

schema/definitions/0.8.0/schema/fmu_meta.json, src/fmu/dataio/datastructure/meta/specification.py, src/fmu/dataio/providers/objectdata/_base.py, src/fmu/dataio/providers/objectdata/_faultroom.py, src/fmu/dataio/providers/objectdata/_provider.py, src/fmu/dataio/providers/objectdata/_tables.py, src/fmu/dataio/providers/objectdata/_xtgeo.py, tests/test_units/test_metadata_class.py, tests/test_units/test_objectdataprovider_class.py
Contributes to #564
Stacked PR on #658
=> ENH: Return BaseModel from spec getters 

docs/example_surface.yml, src/fmu/dataio/dataio.py, src/fmu/dataio/providers/_fmu.py, tests/test_units/test_ert_context.py, tests/test_units/test_fmuprovider_class.py
=> DEP: Drop support for adding jobs.json

src/fmu/dataio/_definitions.py, src/fmu/dataio/providers/objectdata/_base.py, src/fmu/dataio/providers/objectdata/_faultroom.py, src/fmu/dataio/providers/objectdata/_provider.py, src/fmu/dataio/providers/objectdata/_tables.py, src/fmu/dataio/providers/objectdata/_xtgeo.py, tests/test_units/test_filedataprovider_class.py
Works toward #666 
Stacked pr on #676
=> MAINT: Convert efolder into a property

src/fmu/dataio/_definitions.py, src/fmu/dataio/providers/objectdata/_base.py, src/fmu/dataio/providers/objectdata/_faultroom.py, src/fmu/dataio/providers/objectdata/_provider.py, src/fmu/dataio/providers/objectdata/_tables.py, src/fmu/dataio/providers/objectdata/_xtgeo.py, tests/test_units/test_table.py
Toward #666 
Stacked PR on top of #680 #677
Should be the last piece to flip the switch on having this be, or return, a Pydantic model.
=> MAINT: Make layout, table_index properties

schema/definitions/0.8.0/schema/fmu_meta.json, src/fmu/dataio/_definitions.py, src/fmu/dataio/_metadata.py, src/fmu/dataio/dataio.py, src/fmu/dataio/datastructure/meta/content.py, src/fmu/dataio/datastructure/meta/enums.py, src/fmu/dataio/providers/objectdata/_base.py, src/fmu/dataio/providers/objectdata/_faultroom.py, src/fmu/dataio/providers/objectdata/_provider.py, src/fmu/dataio/providers/objectdata/_tables.py, src/fmu/dataio/providers/objectdata/_xtgeo.py, tests/test_units/test_metadata_class.py, tests/test_units/test_objectdataprovider_class.py
=> ENH: Make ObjectDataProviders return Pydantic models

schema/definitions/0.8.0/schema/fmu_meta.json, src/fmu/dataio/dataio.py, src/fmu/dataio/datastructure/configuration/global_configuration.py, src/fmu/dataio/datastructure/meta/enums.py, src/fmu/dataio/datastructure/meta/meta.py, tests/conftest.py, tests/test_units/test_metadata_class.py
=> MAINT: Rename AccessLevel enum to Classification

src/fmu/dataio/dataio.py, tests/test_units/test_metadata_class.py
=> DEP: Input rep_include from config

.github/workflows/ci-fmudataio.yml
=> BLD: Pin fmu-sumo-uploader == 1.0.7

schema/definitions/0.8.0/schema/fmu_meta.json, src/fmu/dataio/_metadata.py, src/fmu/dataio/datastructure/meta/meta.py, tests/test_units/test_metadata_class.py
=> DOC: Complete `meta` docstrings

tests/test_units/test_rms_context.py
Address #719, but only partially.
In this case, using `monkeypath.chdir()` is not possible since the fixture proposed here has `scope=module`, while `monkeypatch` is restricted to `scope="function"`. Scope `module` is chosen here as log at as tests within a module does not interfer, and will be much faster to run.
Also, since the fixture on applied in one module, it is placed in top of that module, instead of in `conftest.py`.
=> TST: improve use of fixtures in rms-related tests

docs/src/preparations.rst
=> DOC: Fix wrong case metadata filename

docs/src/dataio_3_migration.rst, docs/src/index.rst, src/fmu/dataio/dataio.py
=> DOC: Add fmu-dataio 3.0 migration guide

.github/workflows/ci-fmudataio.yml
=> BLD: Unpin fmu-sumo-uploader

pyproject.toml, schema/definitions/0.8.0/schema/fmu_results.json
=> BLD: Unpin Pydantic 2.7.0

src/fmu/dataio/_metadata.py, src/fmu/dataio/_model/global_configuration.py, src/fmu/dataio/dataio.py, src/fmu/dataio/providers/_fmu.py, src/fmu/dataio/providers/objectdata/_base.py, tests/test_units/test_dataio.py, tests/test_units/test_metadata_class.py
=> MAINT: Keep config as pydantic model

src/fmu/dataio/dataio.py
=> ENH: Reduce warnings emitted when config is not valid

src/fmu/dataio/providers/_fmu.py, tests/test_units/test_fmuprovider_class.py
=> BUG: Resolve restart_path correctly

schema/definitions/0.8.0/schema/fmu_results.json, src/fmu/dataio/_model/root.py
=> FIX: Add `data.geometry` as contractual

docs/src/dataio_3_migration.rst, src/fmu/dataio/aggregation.py
=> DEP: Add deprecation warning to generate_aggregation_metadata()

pyproject.toml, src/fmu/dataio/providers/objectdata/_base.py, tests/test_units/test_dataio.py, tests/test_units/test_ert_context.py, tests/test_units/test_filedataprovider_class.py, tests/test_units/test_prerealization_surfaces.py, tests/test_units/test_rms_context.py
Resolves #799
Was a bit unsure weather to keep this warning or not? to me it feels a bit over-verbose ? but I can introduce it again 😄 @jcrivenaes
=> MAINT: Remove warning when using forcefolder

docs/src/dataio_3_migration.rst, src/fmu/dataio/_metadata.py, src/fmu/dataio/dataio.py, src/fmu/dataio/providers/_filedata.py, tests/test_units/test_filedataprovider_class.py
=> DEP: Always compute checksum_md5 when generating metadata

src/fmu/dataio/dataio.py
=> BUG: Ignores error reported by Mypy

radixconfig.yaml
=> CI: Add 'staging' radix environment

src/fmu/dataio/scripts/create_case_metadata.py
This serves mostly as a test to understand the best pattern of getting a staging schema deployment. If it goes well it should appear on the Radix console which now has a staging environment.
=> Merge 2.5.1 into staging

docs/ext/pydantic_autosummary/__init__.py, docs/ext/pydantic_autosummary/generate.py, pyproject.toml, src/fmu/dataio/dataio.py
Resolves #836 
Also fixes an indentation issue.
=> DOC: Fix pydantic_autosummary for sphinx-rtd >= 3

src/fmu/dataio/_utils.py, src/fmu/dataio/export/rms/_utils.py, src/fmu/dataio/export/rms/inplace_volumes.py, tests/test_export_rms/test_export_rms_volumetrics.py
=> FIX: Remove config_path as argument to rms volumes export

src/fmu/dataio/_model/root.py
Resolves #891
Came across this when doing some prep reading for inplace volumes payload schema. Pydantic will use the correct 2020-12 schema if the schema generator mode is set to validation, and also offers a little more convenience functionality for modifying the dumped schema. This also allows the list of contractual items to be more accessible.
=> MAINT: Use schema generator to modify schema dump

src/fmu/dataio/export/rms/inplace_volumes.py, tests/test_export_rms/test_export_rms_volumetrics.py
=> ENH: Set table_index explicit in inplace_volume export

.github/workflows/ci-fmudataio.yml
=> CI: Pin sumo-uploader for Python 3.8 workflow

src/fmu/dataio/_products/inplace_volumes.py, src/fmu/dataio/export/_enums.py, src/fmu/dataio/export/rms/_enums.py, src/fmu/dataio/export/rms/inplace_volumes.py, tests/test_export_rms/test_export_rms_volumetrics.py
Resolves #920 
Stacked on #894
=>  ENH: Enumerate inplace volumes table columns

schema/definitions/0.8.0/schema/fmu_results.json, src/fmu/dataio/_model/data.py, src/fmu/dataio/_model/enums.py, src/fmu/dataio/_model/product.py, src/fmu/dataio/_model/root.py, src/fmu/dataio/providers/objectdata/_base.py, src/fmu/dataio/providers/objectdata/_provider.py
PR that closes #876
Tests will be added once we add functionality to set the `product` in the metadata
=> ENH: Add data.product to schema

schema/definitions/0.8.0/schema/fmu_results.json, src/fmu/dataio/_model/product.py
Resolves a follow-up AJV validation error
=> FIX: Make volumes product name required

src/fmu/dataio/export/rms/inplace_volumes.py
PR to replace some strings in the `inplace_volumes` with enum values instead.
=> MAINT: Replace column strings with enums in inplace_volumes

.github/workflows/schemas-up-to-date.yml, .gitignore, tools/schema-validate-ajv.mjs
=> CI: Validate schema with AJV

src/fmu/dataio/aggregation.py, src/fmu/dataio/dataio.py
Resolves #1113 
This removes the `_validate_variable` function which was used to validate the input arguments coming in through `export/generate_metadata` - both that it was a valid dataclass field and a had the correct type. 
This function would eventually be removed in fmu-dataio 3.0.0 when this pattern is no longer supported. 
It is removed a bit early now since it started failing after converting to new type hinting style (it does not handle unions), but I still kept a check that an input argument given to is actually a field in the given dataclass .
There are a several existing tests using and testing this old pattern.
=> FIX: Remove failing _validate_variable function

examples/example_metadata/fmu_case.yml, examples/example_metadata/polygons_field_outline.yml, examples/example_metadata/polygons_field_region.yml, examples/example_metadata/preprocessed_surface_depth.yml, examples/example_metadata/surface_depth.yml, examples/example_metadata/surface_fluid_contact.yml, examples/example_metadata/surface_seismic_amplitude.yml, examples/example_metadata/table_inplace_volumes.yml, schemas/0.10.0/fmu_results.json, src/fmu/dataio/_models/fmu_results/enums.py, src/fmu/dataio/_models/fmu_results/fmu_results.py
Resolves #1124 
Add a new class of surfaces which can represent several different content types.
=> ENH: Add new class 'triangulated_surface' (#1124)

docs/src/standard_results/field_outline.md, docs/src/standard_results/initial_inplace_volumes.md, docs/src/standard_results/structure_depth_fault_lines.md, docs/src/standard_results/structure_depth_isochores.md, docs/src/standard_results/structure_depth_surfaces.md
Resolves #1130 
Added the relevant security level information to each standard result documentation.
=> DOC: Add security classification for standard results

src/fmu/dataio/_readers/tsurf.py, tests/test_units/test_reader_tsurf.py
Resolves #1188 
Added bounding box to TSurf class, including test
=> ENH: add bounding box to TSurf class (#1188)

examples/example_metadata/fmu_case.yml, examples/example_metadata/polygons_field_outline.yml, examples/example_metadata/polygons_field_region.yml, examples/example_metadata/preprocessed_surface_depth.yml, examples/example_metadata/surface_depth.yml, examples/example_metadata/surface_fluid_contact.yml, examples/example_metadata/surface_seismic_amplitude.yml, examples/example_metadata/table_inplace_volumes.yml, schemas/0.11.0/fmu_results.json, src/fmu/dataio/_models/fmu_results/enums.py, src/fmu/dataio/_models/fmu_results/fmu_results.py
Resolves #1128 
Added the `TSurf` file format to `FileFormat` enum
=> SCHEMA: Add 'tsurf' to FileFormat's enum (#1128)

src/fmu/dataio/_readers/tsurf.py, tests/test_units/test_reader_tsurf.py
Resolves #1203 
Allow TSurf file import/export via memory buffer
Improve handling of large files by importing file line by line instead of loading entire file into memory on import
=> ENH: TSurf file import/export via memory buffer, import file line by line

nginx.conf
Resolves #issue
Fix a typo in https://github.com/equinor/fmu-dataio/pull/1214
=> FIX: set correct autoindex_format in nginx config

examples/example_metadata/fmu_case.yml, examples/example_metadata/polygons_field_outline.yml, examples/example_metadata/polygons_field_region.yml, examples/example_metadata/preprocessed_surface_depth.yml, examples/example_metadata/surface_depth.yml, examples/example_metadata/surface_fluid_contact.yml, examples/example_metadata/surface_seismic_amplitude.yml, examples/example_metadata/table_inplace_volumes.yml, schemas/0.12.0/fmu_results.json, src/fmu/dataio/_models/fmu_results/fmu_results.py
=> SCHEMA: Bump fmu_results to 0.12.0

src/fmu/dataio/_utils.py, src/fmu/dataio/providers/objectdata/_xtgeo.py, tests/test_units/test_rms_context.py
Resolves #1294 
PR to skip populating `data.geometry` if the config is invalid --> objects are exported without metadata anyway and this geometry linking is not relevant. 
Also added a check that the geometry points to an existing file.
=> FIX: Handle missing geometry metadata

src/fmu/dataio/_readers/tsurf.py, tests/test_units/test_reader_tsurf.py
Resolves #1298
Changed a list to a dict, fixed issues with mypy
=> FIX: change list to dict, fix mypy issues

src/fmu/dataio/scripts/create_case_metadata.py
=> DOC: Update argument list for WF_CREATE_CASE_METADATA
