- src/fmu/dataio/_export_item.py
I think #40 needs more discussion. Meanwhile, propose to remove the outgoing `data.spec.undef` value for tables to avoid mixed-type in the output `data.spec.undef` for surfaces is a float and make table data validate against current 0.8.0 schema.
> remove data.spec.undef from outgoing table metadata

- src/fmu/dataio/dataio.py
- tests/test_fmu_dataio_generic.py
grid_model reference is not known to fmu.dataio, hence proposing that it is passed as argument. Further, grid_model is a naturally defining field. Data exported from one grid_model is often (usually?) also exported from all grid_models.
> add grid_model argument and function to process it

- src/fmu/dataio/_export_item.py
- tests/test_fmu_dataio_surface.py
Solving #57 
For later surface subtypes (e.g. structuredsurface), the classname should also be `surface`.
> Use surface as class

- src/fmu/dataio/_utils.py
- tests/data/drogon/ertrun1/realization-0/iter-0/parameters_justified.txt
- tests/test_fmu_dataio_utils.py
Solving #53 by stripping whitespace from parameters.txt contents before parsing it. Also added testing for a negative float value, and renamed the `buffer` variable to `buffer_` to avoid overwriting the `buffer` type.
> Read justified-formatted parameters txt

- src/fmu/dataio/_export_item.py
- tests/test_export_item.py
Purpose is to fail when required content is not provided. Currently, giving a string will pass through even if that string indicates that this content should have additional required information.
Solving #83, but probably needs a refactoring at some point. I assume this is the idea behind #20.
> content fluid contact

- pyproject.toml
- requirements/requirements.txt
- src/fmu/dataio/_export_item.py
- tests/test_fmu_dataio_table.py
Use of pyarrow requires a higher numpy version than RMS 12.0 (and before) has. Adjust dependency on pyarrow install and adjust code according to this, so it will not be installed for python versions <= 3.6.1 (which is the version RMS 11* and 12.0* uses). Also conditional use in code.
> Pyarrow import granularity

- mypy.ini
- requirements/requirements.txt
- setup.cfg
- src/fmu/dataio/_utils.py
- src/fmu/dataio/dataio.py
- tests/test_fmu_dataio_utils.py
The nesting of parameters dictionary is specific to fmu-dataio. Make it more explicit
by putting it in a different function
> Use semeio for parameter parsing, make nesting explicit

- src/fmu/dataio/dataio.py
Solving #108 
This PR is putting the export of `jobs.json` contents. These constitute a major part of outgoing metadata, and puts unneeded strain on later applications of the metadata. Until a use case is clear, suggest pausing it. It is still parsed, as the `runid` is fetched from it.
Also suggest to keep this on the list of things expected to get directly from ERT in the future.
> Pausing export of jobs.json content

- README.md
Cosmetics on the ReadMe. Removing redundant build status shield & move it to top of section. The shield show status on Radix build.
> Buildstatus shield

- pytest.ini
- src/fmu/dataio/dataio.py
- tests/data/drogon/global_config2/not_valid_yaml.yml
- tests/test_fmu_dataio_generic.py
Either, in case the `config` key is not present or set None:
- Set env variable  ~~`FMU_DATAIO_CONFIG`~~ `FMU_GLOBAL_CONFIG` to point to the YAML file that shall be input to the `config` key
- ~~Look for `../../fmuconfig/output/global_variables.yml`~~
This will simplify for e.g. script running in an ERT forward model
> Detect global config from env etc

- src/fmu/dataio/_export_item.py
- tests/test_export_item.py
Solving #156 
Ref #150 - `truncated` is a valid field for `fluid_contact` but fmu-dataio did not allow it. This PR allows it.
> allow fluid_contact.truncated according to schema

- src/fmu/dataio/_export_item.py
- src/fmu/dataio/dataio.py
- tests/test_fmu_dataio_surface.py
Responding to issue #187 but keep as draft
* Restrict `subfolder` fields so it cannot contain path information
* Add a `forcefolder` key for nonstandards file locations
~~* Rename `runpath` to `basepath` to be more generic~~
> Allow nonstandard folders

- schema/definitions/0.8.0/examples/surface_depth.yml
- schema/definitions/0.8.0/schema/fmu_results.json
- src/fmu/dataio/_export_item.py
- src/fmu/dataio/dataio.py
- tests/test_export_item.py
Adding tagname to the metadata to align with Webviz and to achieve uniqueness.
* Adding tagname to the schema, making it contractual but not required.
* Keeping tagname non-required to be backwards compatible.
> Tagname to metadata

- docs/examples.rst
Fixing a bug that made it through in #210 
In current `main`, the aggregation example does not show up in the docs.
> make aggregation example show in docs

- src/fmu/dataio/_filedata_provider.py
- tests/test_units/test_prerealization_surfaces.py
This was found when running the Drogon test example
> Corrected observation to observations

- src/fmu/dataio/_utils.py
- src/fmu/dataio/dataio.py
- tests/test_units/test_aggregated_surfaces.py
Solving #221 
- Change the API - no longer accept non-string input for `aggregation_id`
- Returned `aggregation_id` is now a string
- Returned `aggregation_id` is now independent of sorting (same input give same output, regardless of input sorting)
- Add some more tests to it
> Aggregation_id

- schema/definitions/0.8.0/schema/fmu_results.json
Replace implications with `if`-`then` fields in the schema, which should make it easier to read and maintain.
> Schema implications

- schema/definitions/0.8.0/examples/aggregated_surface_depth.yml
- schema/definitions/0.8.0/examples/polygons_field_outline.yml
- schema/definitions/0.8.0/examples/surface_depth.yml
- schema/definitions/0.8.0/examples/surface_fluid_contact.yml
- schema/definitions/0.8.0/examples/surface_seismic_amplitude.yml
- schema/definitions/0.8.0/schema/fmu_results.json
Solving #235 
Element is already added to outgoing metadata, but was not included in the schema.
> add file.size_bytes to schema and examples

- src/fmu/dataio/_fmu_provider.py
- src/fmu/dataio/_utils.py
- src/fmu/dataio/dataio.py
- tests/test_units/test_fmuprovider_class.py
Typically found in prehook work flows, where fmu_context=case an casepath is given explicitly.
> Fix issues for fmu_context="case"

- src/fmu/dataio/hook_implementations/jobs.py
- src/fmu/dataio/scripts/create_case_metadata.py
Importing the deprecated package name can trigger
a deprecation warning.
> Reverse order of ert.shared vs ert_shared

- schema/definitions/0.8.0/examples/preprocessed_surface_depth.yml
- schema/definitions/0.8.0/schema/fmu_results.json
- tests/test_schema/test_schema_logic.py
When creating pre-processed data, `fmu.realization` nor `fmu.aggregation` will be present. Hence cannot require these.
> add pre-processed example and make fmu.realization not required

- schema/definitions/0.8.0/schema/fmu_results.json
Solve problem with using the `not` keyword directly. Trying the `dependencies` keyword instead. The intention is to allow either `fmu.realization`, `fmu.aggregation` or none of them - never both.
> Use dependencies keyword on aggregation vs realization

- src/fmu/dataio/_filedata_provider.py
- src/fmu/dataio/_objectdata_provider.py
- src/fmu/dataio/dataio.py
- tests/test_units/test_prerealization_surfaces.py
Solves #282, when the subsequent FMU job is ran on preprocessed data.
> Fix a bug when preprocessed data use a subfolder

- schema/definitions/0.8.0/schema/fmu_results.json
Retrofitting to match existing behavior of fmu-dataio where the `data.time` attribute is a dict/object, not a list.
> allow data.time to be object/dict

- src/fmu/dataio/dataio.py
- tests/test_units/test_prerealization_surfaces.py
Bugfix; when preprocessed data were merged in a FMU run, the original tagname was not applied in the result.
> Fix propagation of tagname  when preprocessed

- src/fmu/dataio/_metadata.py
- src/fmu/dataio/_utils.py
- src/fmu/dataio/dataio.py
- tests/test_units/test_prerealization_surfaces.py
- tests/test_units/test_rms_context.py
Now the true stratigraphic name is propagated correctly from pre- processed to FMU merged result. Some refaktor/simplification; needed variables such as input name, tagname and subfolder from preprocessed are tmp stored under a _preprocessed field in the metadata.
> Ensure correct data.name when preprocessed/merged

- src/fmu/dataio/_metadata.py
- src/fmu/dataio/dataio.py
- tests/test_units/test_dataio.py
- tests/test_units/test_prerealization_surfaces.py
The `fmu.dataio` is now being implemented in the next release of demo case Drogon, and this is applied further by numerous assets as a template. Since SUMO still is too immature for broad implementation, a request exists to make it possible for `dataio` to work with with "current" global config, at least for a time period (cf. @rnyb).
The behaviour now is that if  e.g. `masterdata` section is missing, the date file will be exported but without the metadata `.yml` file.
This request was partially solved by #269, when the global config is an empty dict.
> Adjust behaviour when invalid metadata

- schema/definitions/0.8.0/examples/aggregated_surface_depth.yml
- schema/definitions/0.8.0/examples/polygons_field_outline.yml
- schema/definitions/0.8.0/examples/preprocessed_surface_depth.yml
- schema/definitions/0.8.0/examples/surface_depth.yml
- schema/definitions/0.8.0/examples/surface_fluid_contact.yml
- schema/definitions/0.8.0/examples/surface_seismic_amplitude.yml
- schema/definitions/0.8.0/schema/fmu_results.json
- src/fmu/dataio/_objectdata_provider.py
- src/fmu/dataio/_utils.py
- src/fmu/dataio/dataio.py
- tests/test_schema/test_schema_logic.py
- tests/test_units/test_dataio.py
- tests/test_units/test_initialize_case.py
- tests/test_units/test_metadata_class.py
Following discussions and with reference to #195 this PR updates the metadata examples and the schema to assume data.time as a dictionary.
> lock data.time to a dictionary with t0 and t1

- schema/definitions/0.8.0/examples/polygons_field_region.yml
- schema/definitions/0.8.0/schema/fmu_results.json
- src/fmu/dataio/_definitions.py
- tests/test_schema/test_schema_logic.py
- tests/test_units/test_dataio.py
Solving/contributing to #200 
This PR allows `field_region` as content. It is singular, and may be joined by `field_regions` in the future for objects containing many regions. This is request from REP and JS, purpose is to the able to effectively and consistently identify specific type of region from FMU results. The more generic `regions` is already allowed, but will include other types of regions as well.
> allow field_region as content

- schema/definitions/0.8.0/examples/table_inplace.yml
- schema/definitions/0.8.0/schema/fmu_results.json
Solve #309 
Include `data.size` and `data.columns` in schema, and make `data.columns` contractual.
> data.size and data.columns in schema

- src/fmu/dataio/_fmu_provider.py
- tests/conftest.py
- tests/test_units/test_fmuprovider_class.py
Add fmu_restart metadata on iteration level based on environment variable RESTART_FROM_PATH that user need to specify in ERT config file.
Typical setup for restart in the same case as AHM 
````
DEFINE <RESTART_DIR>      iter-3       -- name of the history folder to restart from
DEFINE <RESTART_CASE>     ../../../<RESTART_DIR>/eclipse/model/<ECLIPSE_NAME>-<IENS>   -- Note: path is relative to eclipse/model
DEFINE <RESTART_REPORT>   82
SETENV RESTART_FROM_PATH  ../<RESTART_DIR>  -- Note: path is relative to iteration path
````
Typical setup for restart in a new (different) case from AHM
````
DEFINE <RESTART_BASE_CASE>     01_drogon_ahm_sumo
DEFINE <RESTART_DIR>      iter-3       -- name of the history folder to restart from
DEFINE <RESTART_PATH> …
```
> Add fmu_restart metadata on iteration level

- requirements/requirements.txt
- src/fmu/dataio/_fmu_provider.py
- src/fmu/dataio/_utils.py
- tests/test_units/test_metadata_class.py
Instead of using the standard YAML loader, reuse the `fmu.config yaml_load()` function which opens for reading `YAML` files on
FMU input format (in-house extended `YAML` syntax). 
Closes #328
> Reuse fmuconfig yaml load

- .readthedocs.yml
Action to mitigate coming deprecation in readthedocs. (system-packages will not be supported from Sept. 2023)
> Update readthedocs config.

- src/fmu/dataio/_definitions.py
The first step in an attempt to introduce staging to the fmu schema. We would like to use the dev version of the schema in sumo-dev and the prod schema in sumo-prod. This will hopefully allow us to experiment and make changes to the structure of the schema and test it in sumo without the fear of introducing problems in production.
The plan is to make changes to the uploader where we will set `$schema` to the dev url if `SUMO_ENV` == `dev`. Otherwise the default value will remain, which is now the prod url.
> Populate metadata with prod url instead of dev

- schema/definitions/0.8.0/examples/dictionary_parameters.yml
- schema/definitions/0.8.0/schema/fmu_results.json
- tests/test_schema/test_schema_logic.py
This schema change makes `data.spec` required only when `class` is one of [`table`, `surface`].
Related to #365
> Require data.spec only on certain data types

- src/fmu/dataio/_utils.py
- tests/test_units/test_prerealization_surfaces.py
Partially solve #352 by reusing `access` from preprocessed metadata, not re-generating.
> Do not overwrite access when using preprocessed metadata.

- schema/definitions/0.8.0/examples/table_wellpicks.yml
- schema/definitions/0.8.0/schema/fmu_results.json
- src/fmu/dataio/_definitions.py
- tests/test_schema/test_schema_logic.py
Partly solve #369 
`fmu-dataio` currently allows `ExportData` to be called without `content` explicitly set. It will in those cases default to a generic value. However, we do not want those data to be available to any data consumer. Long-term, we will require that the `content` argument is used. Short-term (this PR), we will not validate documents with the default schema.
This PR includes the whitelisted contents into the schema. It also introduces a test which fails if the list of contents in the code becomes out of synch with the list in the schema.
> Validate content value

- src/fmu/dataio/_objectdata_provider.py
- src/fmu/dataio/dataio.py
- tests/test_units/test_table.py
This PR removes the table_index_values field from the metadata
Testing on large datasets like Snorre shows that the table_index_values is not sustainable.
There are also many problems with json serializability related to this field.
> Remove table_index_values

- src/fmu/dataio/_objectdata_provider.py
- src/fmu/dataio/dataio.py
- tests/test_units/test_dataio.py
- tests/test_units/test_prerealization_surfaces.py
Address issue #379
The handling of content is moved to _object_data_provider, and also check that  the fmu_context is not "case"
> Improve handling of warning when missing content

- src/fmu/dataio/dataio.py
- tests/test_units/test_dataio.py
Solve #383. But there are probably better ways. See issue for details.
> Detect and warn if empty entries in config.stratigraphy

- src/fmu/dataio/_metadata.py
- tests/test_units/test_metadata_class.py
Solve #397 
This PR adds (local) time zone offset to the datetime in `tracklog`.
E.g. `2023-12-14T15:22:45.729902` -> `2023-12-14T15:22:45.729902+01:00`
Issue states "ZULU" time. In this PR, I have deliberately chosen to implement local time instead. I figure that the most important element here is to include time zone offset. I don't currently have full overview of what possible confusion we could risk if these time stamps are not on local time.
> Include time zone offset in tracklog datetime.

- src/fmu/dataio/_metadata.py
- tests/test_units/test_metadata_class.py
Solving #397, related to #398.
Change from local time to UTC time in tracklog datetimes.
Somewhat clumsy to do this across two PR's, but OK, effect is the same. We want these two commits to be distinct.
> Datetime in tracklog on UTC time.

- examples/s/d/nn/xcase/realization-0/iter-0/any/bin/export_volumetables.py
- src/fmu/dataio/_definitions.py
Solve #378 
As we seem to have converged on using `volumes`, this PR removes the unused contents `volumetrics` and `inplace_volumes`.
> Do not allow contents volumetrics and inplace_volumes.

- src/fmu/dataio/_metadata.py
- src/fmu/dataio/dataio.py
- tests/test_units/test_dataio.py
- tests/test_units/test_metadata_class.py
Solve #319 
This PR makes `display.name` always populated in produced metadata.
- When `display_name` argument is given, use it to populate `display.name`
- When `display_name` not given, populate `display.name` with `data.name`
> Use display_name when explicitly given

- examples/s/d/nn/_project/aggregate_surfaces.py
- examples/s/d/nn/xcase/realization-0/iter-0/any/bin/export_volumetables.py
- examples/s/d/nn/xcase/realization-0/iter-0/rms/bin/export_faultpolygons.py
- src/fmu/dataio/__init__.py
- src/fmu/dataio/_design_kw.py
- src/fmu/dataio/_filedata_provider.py
- src/fmu/dataio/_fmu_provider.py
- src/fmu/dataio/_metadata.py
- src/fmu/dataio/_oyaml.py
- src/fmu/dataio/_utils.py
- src/fmu/dataio/dataio.py
- src/fmu/dataio/scripts/create_case_metadata.py
- tests/conftest.py
- tests/test_schema/test_schema_logic.py
- tests/test_units/test_dataio.py
- tests/test_units/test_dictionary.py
- tests/test_units/test_fmuprovider_class.py
- tests/test_units/test_initialize_case.py
- tests/test_units/test_metadata_class.py
- tests/test_units/test_table.py
Updates code to 38plus friendly syntax.
```bash
find . -type f -name '*.py' | xargs -n1 pyupgrade --py38-plus
```
> Update codebase to py38

- .github/workflows/ci-fmudataio.yml
- .github/workflows/fmudataio-documention.yml
- .github/workflows/fmudataio-publish-pypi.yml
- .github/workflows/linting.yml
- .github/workflows/mypy.yml
- .gitignore
- mypy.ini
- pyproject.toml
- src/fmu/dataio/_definitions.py
- src/fmu/dataio/_design_kw.py
- src/fmu/dataio/_filedata_provider.py
- src/fmu/dataio/_fmu_provider.py
- src/fmu/dataio/_metadata.py
- src/fmu/dataio/_objectdata_provider.py
- src/fmu/dataio/_oyaml.py
- src/fmu/dataio/_utils.py
- src/fmu/dataio/dataio.py
- src/fmu/dataio/hook_implementations/jobs.py
- src/fmu/dataio/scripts/create_case_metadata.py
- tests/test_units/test_aggregated_surfaces.py
Merge after: https://github.com/equinor/fmu-dataio/pull/405
> Complete mypy type coverage for entire codebase

- src/fmu/dataio/_metadata.py
- src/fmu/dataio/_utils.py
- src/fmu/dataio/dataio.py
> Simplify export_file_compute_checksum_md5 function

- src/fmu/dataio/_utils.py
- tests/conftest.py
- tests/test_units/test_utils.py
Test coverage hunting: ~ 14% more coverage in the src/fmu/dataio/_utils.py 
Before:
```python
(dataio) ➜  fmu-dataio git:(main) coverage report --include=src/fmu/dataio/_utils.py 
Name                       Stmts   Miss  Cover
----------------------------------------------
src/fmu/dataio/_utils.py     226     45    80%
----------------------------------------------
TOTAL                        226     45    80%
````
After:
```python
(dataio) ➜  fmu-dataio git:(more-utils-tests) ✗ coverage report --include=src/fmu/dataio/_utils.py
Name                       Stmts   Miss  Cover
----------------------------------------------
src/fmu/dataio/_utils.py     218     12    94%
----------------------------------------------
TOTAL                        218     12    94%
```
> Add utils tests

- tests/test_units/test_dictionary.py
> TST: Extra parameters parsing tests

- CONTRIBUTING.md
- README.md
- docs/conf.py
- docs/contributing.rst
- docs/index.rst
- docs/installation.rst
- pyproject.toml
Copy of https://github.com/equinor/xtgeo/blob/main/docs/contributing.rst with some modifications (dropped the section about how to run stuff in RMS)
> DOC: Add contributing document

- src/fmu/dataio/_metadata.py
- src/fmu/dataio/_utils.py
- src/fmu/dataio/dataio.py
> CLN: Remove extension argument

- src/fmu/dataio/_objectdata_provider.py
- src/fmu/dataio/_utils.py
- tests/conftest.py
- tests/test_units/test_table.py
Im not 100% sure if this is better, i just hate it when you have to track two variables. 
This might also be an option, but its a bit much for this case i thing. 
https://docs.python.org/3/library/importlib.html#implementing-lazy-imports
> CLN: Lazy import pyarrow

- schema/definitions/0.8.0/examples/surface_depth.yml
- schema/definitions/0.8.0/schema/fmu_results.json
- src/fmu/dataio/_metadata.py
- src/fmu/dataio/_utils.py
- tests/test_units/test_metadata_class.py
- tests/test_units/test_utils.py
Solve #387 
This PR includes some selected system information to the tracklog `created` entry when exporting data with fmu-dataio. The selected information include the current version of `fmu-dataio` used and the Komodo release when running in a Komodo environment.
The purpose of this is to ease debugging and user support, i.e. "as a developer I would like to know which version of fmu-dataio was used, so that I can understand the users context, detect and solve problems quicker."
Put into metadata the answer to the most common first debugging question: "Which version of fmu-dataio is the user running?"
Updated `tracklog` entry in produced metadata:
```yaml
tracklog:
- datetime: 2020-10-28T14:28:02
user:
id: peesv
event: created
sysinfo:   # New ⚡
fmu-dataio:
version: 1.2.3
komodo: # only …
```
> Dump selected sysinfo to tracklog.

- src/fmu/dataio/_design_kw.py
- src/fmu/dataio/_filedata_provider.py
- src/fmu/dataio/_fmu_provider.py
- src/fmu/dataio/_logging.py
- src/fmu/dataio/_metadata.py
- src/fmu/dataio/_objectdata_provider.py
- src/fmu/dataio/_utils.py
- src/fmu/dataio/dataio.py
- src/fmu/dataio/scripts/create_case_metadata.py
- tests/conftest.py
- tests/test_units/test_aggregated_surfaces.py
- tests/test_units/test_dataio.py
- tests/test_units/test_ert2_context.py
- tests/test_units/test_fmuprovider_class.py
- tests/test_units/test_initialize_case.py
- tests/test_units/test_rms_context.py
Using verbosity and setLevel within the library is an antipattern. 
The approach shall be that the end client script sets the logging level, format, etc. instead.
Closes #270
> ENH: replace verbosity with standard logging patterns

- docs/examples.rst
- docs/overview.rst
- docs/preparations.rst
- src/fmu/dataio/dataio.py
Some small things I noticed whilst reading the documentation.
- Minor grammar/spelling fixes
- Markdown bullet points that rst didn't translate
- yml identation
- sphinx warning
> DOC: fix minor documentation errors

- .gitignore
- docs/preparations.rst
- examples/s/d/nn/xcase/realization-0/iter-0/any/bin/export_grid3d.py
- examples/s/d/nn/xcase/realization-0/iter-0/any/bin/export_volumetables.py
- examples/s/d/nn/xcase/realization-0/iter-0/rms/bin/export_a_surface.py
- examples/s/d/nn/xcase/realization-0/iter-0/rms/bin/export_faultpolygons.py
- examples/s/d/nn/xcase/realization-0/iter-0/rms/bin/export_propmaps.py
- examples/s/d/nn/xcase/realization-1/iter-0/rms/bin/export_a_surface.py
- examples/s/d/nn/xcase/realization-9/iter-0/rms/bin/export_a_surface.py
The example scripts generated warnings about passing the deprecated `verbosity` keyword and the docs also referenced it. The scripts were modified to set the logging level to `WARNING` which seems a reasonable example for users to follow as INFO may be more than they care about.
> FIX: Remove deprecated `verbosity` from examples

- pyproject.toml
Can be unpined due to https://github.com/pydantic/pydantic/issues/8665 is closed/fixed.
> FIX: Unpin pydantic lt. 2.6

- tests/conftest.py
- tests/test_units/test_dataio.py
- tests/test_units/test_metadata_class.py
Still a few warnings left (3), they need more effort. Want to merge this first to limit dev. noise.
> CLN: Clean up pytest global configuration user warnings

- docs/index.rst
- docs/installation.rst
- docs/overview.rst
- docs/preparations.rst
This PR solves #441 but also includes some general restructuring and improvements to the documentation.
> DOC: Improve documentation

- examples/run_examples.sh
- examples/s/d/nn/xcase/realization-0/iter-0/any/bin/export_grid3d.py
- pyproject.toml
- src/fmu/dataio/_definitions.py
- src/fmu/dataio/_filedata_provider.py
- src/fmu/dataio/_fmu_provider.py
- src/fmu/dataio/_metadata.py
- src/fmu/dataio/_utils.py
- src/fmu/dataio/dataio.py
- tests/conftest.py
- tests/test_units/test_dictionary.py
- tests/test_units/test_enum_classes.py
- tests/test_units/test_ert_context.py
- tests/test_units/test_fmuprovider_class.py
- tests/test_units/test_rms_context.py
This is a bigger PR where we go from parsing file paths in order to detect "running in FMU", to look for defined environment variables from ERT runs.
In doing so, some refactorisering is done, in particular for the _FmuProvider class (renamed to FmuProvider) to have a cleaner interface with the calling metadata.py module.
Resolves: https://github.com/equinor/fmu-dataio/issues/368
> ENH: Apply ERT env variables in FMU runs

- src/fmu/dataio/_objectdata_provider.py
Addresses: https://github.com/equinor/fmu-dataio/issues/457
> CLN: Construct BoundingBox using pydantic

- schema/definitions/0.8.0/schema/fmu_meta.json
- src/fmu/dataio/_metadata.py
- src/fmu/dataio/datastructure/meta/meta.py
- tests/test_units/test_metadata_class.py
Resolves: https://github.com/equinor/fmu-dataio/issues/387
Schema will be updated as soon as we decide to publish a new schema
```python
python -c"from pprint import pp; from fmu.dataio._metadata import generate_meta_tracklog; pp(generate_meta_tracklog())"
[{'datetime': '2024-02-12T13:46:27.159655Z',
'event': 'created',
'user': {'id': 'xxxxxx'},
'sysinfo': {'fmu-dataio': {'version': '2.1.1.dev3+gbb36c6a'},
'operating_system': {'hostname': 'AC-W6JD2YH37N',
'operating_system': 'macOS-14.2.1-arm64-arm-64bit',
'release': '23.2.0',
'system': 'Darwin',
'version': 'Darwin Kernel Version 23.2.0: '
'Wed Nov 15 21:55:06 PST 2023; '
'root:xnu-10002.61.3~2/RELEASE_ARM64_T6020'}}}]
```
> ENH: Add platform field to event-tracklog

- src/fmu/dataio/_definitions.py
- src/fmu/dataio/_objectdata_provider.py
- tests/test_units/test_objectdataprovider_class.py
Adressess: https://github.com/equinor/fmu-dataio/issues/457
> CLN: Add dataclass DerivedNamedStratigraphy

- src/fmu/dataio/_definitions.py
- src/fmu/dataio/_filedata_provider.py
- src/fmu/dataio/_metadata.py
- src/fmu/dataio/_objectdata_provider.py
- src/fmu/dataio/dataio.py
- tests/test_units/test_filedataprovider_class.py
- tests/test_units/test_metadata_class.py
- tests/test_units/test_objectdataprovider_class.py
- tests/test_units/test_table.py
Since the modules already is prefixed with _, there is no need to add _ to class etc in those modules.
> CLN: Remove superfluous underscore prefix

- tests/conftest.py
- tests/test_integration/conftest.py
- tests/test_integration/test_wf_create_case_metadata.py
- tests/test_schema/test_pydantic_logic.py
- tests/test_units/test_dataio.py
- tests/test_units/test_prerealization_surfaces.py
- tests/test_units/test_rms_context.py
- tests/test_units/test_utils.py
- tests/utils.py
Adds to #263
This test runs ert with a minimal configuration that just ensures the workflow functions correctly and the fmu case metadata is exported. It does not do more rigorous validating of the exported data.
Utility functions needed to be moved outside of conftest.py in order to add a second confest (they pollute the `from conftest import` namespace). Some convenience fixtures were adjusted.
> TST: Add create_case_metadata integration test

- .github/workflows/ci-fmudataio.yml
- src/fmu/dataio/dataio.py
- src/fmu/dataio/scripts/create_case_metadata.py
- tests/test_integration/conftest.py
- tests/test_integration/test_wf_create_case_metadata.py
- tests/test_units/test_initialize_case.py
Adds to #263 
Running ERT is slow, may be advantageous to add pytest-xdist at some point soon -- but I don't think we're over the threshold where it would make things faster yet.
fmu-sumo-uploader cannot be installed on Python 3.12 due to a dependency on openvds, which does not support Python 3.12, and apparently installation conditions cannot be applied from optional dependencies. This is complicated by fmu-sumo-uploader not being available on PyPI.
So the options are
- Skip adding it to optional dev dependencies and conditional handling in CI, incurring a manual installation
- Skip testing on Python 3.12 in CI
> TST: Add additional create_case_metadata tests

- src/fmu/dataio/_filedata_provider.py
- src/fmu/dataio/_metadata.py
- src/fmu/dataio/_objectdata_provider.py
- src/fmu/dataio/dataio.py
Extends: https://github.com/equinor/fmu-dataio/pull/484
> CLN: Remove last usages of the Any type

- schema/definitions/0.8.0/schema/fmu_meta.json
- src/fmu/dataio/datastructure/meta/meta.py
Extends: #423 
The PR addresses compatibility issues with our JSON schema by removing the `discriminator.mapping` field. This change is necessary to resolve startup failures in `sumo-core` due to schema validation errors with our current JSON schema validator (AJV Validator).
- **Removed `discriminator.mapping`**: Eliminates validation issues, ensuring compatibility with AJV Validator and preventing `sumo-core` startup failures.
For details see: https://equinor.slack.com/archives/C06E3UTGTEV/p1710159496935799
> FIX: Remove discriminator mappings

- src/fmu/dataio/dataio.py
Keep only one validation of the global configuration dictionary in ExportData.  
- The validation step can happen after `self.config` has been established from either input argument, or from yaml-file listed in environment variable.
> CLN: Reduce number of global config validation steps in ExportData

- src/fmu/dataio/_filedata_provider.py
- src/fmu/dataio/_metadata.py
> CLN: Use File pydantic to build file-object

- src/fmu/dataio/datastructure/_internal/internal.py
Rebase and merge after: https://github.com/equinor/fmu-dataio/pull/519
```bash
======================================== warnings summary =========================================
tests/test_units/test_fmuprovider_class.py::test_fmuprovider_prehook_case
/Users/JLOV/.pyenv/versions/3.10.13/envs/dataio/lib/python3.10/site-packages/pydantic/main.py:314: UserWarning: Pydantic serializer warnings:
Expected `url` but got `str` - serialized value may not be as expected
return self.__pydantic_serializer__.to_python(
```
> CLN: Silence pydantic url str warning

- src/fmu/dataio/_fmu_provider.py
- src/fmu/dataio/_metadata.py
- src/fmu/dataio/dataio.py
- tests/test_units/test_dataio.py
Resolves #529 and adds a `ExportData._fmurun` attribute to eliminate the need for initializing a FmuProvider to detect the run environment.
> CLN: Move fmu_context validation for non-fmu runs to ExportData

- src/fmu/dataio/dataio.py
- tests/test_units/test_dataio.py
Prevent overwriting config from environment variable if explicitly given as input argument to ExportData, to avoid confusing behavior for the user.
> FIX: Avoid overwriting config from env if explicitly given

- src/fmu/dataio/_utils.py
- src/fmu/dataio/providers/_objectdata.py
- src/fmu/dataio/providers/_objectdata_base.py
- src/fmu/dataio/providers/_objectdata_xtgeo.py
- tests/test_units/test_objectdataprovider_class.py
- tests/test_units/test_table.py
This further breaks down the object data provider into a more refined API and into more maintainable and testable blocks. An added benefit is more type sanity.
A next step is to move more of these `dict[str, Any]`s (raa!) into more Pydantic... if warranted.
> CLN: Separate spec and bbox derivation

- src/fmu/dataio/_metadata.py
- src/fmu/dataio/providers/_filedata.py
- tests/test_units/test_filedataprovider_class.py
Return `Path` instead of strings in the `FileDataProvider`. The meta.File pydantic model expects Path as input.
> CLN: Change to Path inside FileDataProvider

- schema/definitions/0.8.0/schema/fmu_meta.json
- src/fmu/dataio/datastructure/meta/content.py
Resolves #551 and adds `table_index` to the pydantic model `Content` which all content types are based upon (hence multiple entries in the schema).
> FIX: Add missing table_index to schema

- schema/definitions/0.8.0/schema/fmu_meta.json
- src/fmu/dataio/datastructure/meta/meta.py
Resolves #554
`display.name` is always populated upon creation of the metadata. Either from user input argument, or as the object.name. This object.name probably can be None, so I kept it Optional.
> FIX: Add display to schema

- src/fmu/dataio/providers/_objectdata.py
- src/fmu/dataio/providers/_objectdata_base.py
- tests/test_units/test_objectdataprovider_class.py
Rather than keeping existing metadata as an optional argument for all data providers, if existing metadata exists just create the class directly from it.
> CLN: Create ExistingDataProvider directly

- .github/workflows/ci-fmudataio.yml
- .github/workflows/fmudataio-documention.yml
- .github/workflows/fmudataio-publish-pypi.yml
- .github/workflows/linting.yml
- .github/workflows/mypy.yml
- .github/workflows/schemas-up-to-date.yml
Resolves #562
Also removes some redundant matrix strategies with non-matrix setups, adds some formatting, and specifies an accidentally omitted Python version.
cf. https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
> CI: Update actions using deprecated node.js

- src/fmu/dataio/_metadata.py
- src/fmu/dataio/dataio.py
- src/fmu/dataio/providers/objectdata/_base.py
PR to deprecate and remove the `reuse_metadata_rule` input argument. 
It could most likely be removed without deprecation as discussed with @jcrivenaes.. but since we already have some active deprecations that will be removed in the near future, I added this as well.
Closes https://github.com/equinor/fmu-dataio/issues/567
> CLN: Deprecate reuse_metadata_rule argument

- src/fmu/dataio/_metadata.py
- src/fmu/dataio/case.py
- src/fmu/dataio/dataio.py
- src/fmu/dataio/datastructure/_internal/internal.py
- src/fmu/dataio/providers/objectdata/_base.py
- src/fmu/dataio/providers/objectdata/_provider.py
- src/fmu/dataio/providers/objectdata/_tables.py
- src/fmu/dataio/providers/objectdata/_xtgeo.py
- tests/test_units/test_dataio.py
- tests/test_units/test_metadata_class.py
- tests/test_units/test_objectdataprovider_class.py
PR refactoring the `MetaData` class  into using a pydantic model for creating the internal metadata. Part of https://github.com/equinor/fmu-dataio/issues/457 
This enables early validation upon creation of the metadata, and detection of misalignment between the internal format and the schema.
Almost the entire pydantic model for the schema are reused for the internal meta format, however some adjustments were needed to support e.g. not being in a fmu setting or having invalid config. Going forward we should aim to get them more in sync, so that most metadata produced will be valid for SUMO upload (with exception of preprocessed data).
> CLN: Use pydantic for internal MetaData 

- docs/datastructure.rst
- docs/examples.rst
- examples/run_examples.sh
- examples/s/d/nn/xcase/realization-0/iter-0/rms/bin/export_faultroom_surfaces.py
- examples/s/d/nn/xcase/realization-0/iter-0/rms/output/faultroom/some_faultroom.json
- schema/definitions/0.8.0/examples/surface_faultroom_data.yml
- schema/definitions/0.8.0/schema/fmu_meta.json
- src/fmu/dataio/_utils.py
- src/fmu/dataio/dataio.py
- src/fmu/dataio/datastructure/_internal/internal.py
- src/fmu/dataio/datastructure/meta/content.py
- src/fmu/dataio/datastructure/meta/enums.py
- src/fmu/dataio/datastructure/meta/specification.py
- src/fmu/dataio/providers/objectdata/_faultroom.py
- src/fmu/dataio/providers/objectdata/_provider.py
- src/fmu/dataio/readers.py
- src/fmu/dataio/types.py
- tests/data/drogon/rms/output/faultroom/README.txt
- tests/data/drogon/rms/output/faultroom/ex_faultroom_1.3.1.json
- tests/test_units/test_readers.py
- tests/test_units/test_rms_context.py
> ENH: include (fault) surfaces from FaultRoom plugin

- src/fmu/dataio/dataio.py
- src/fmu/dataio/providers/_fmu.py
- tests/test_units/test_fmuprovider_class.py
The `model` key format in the global_configuration is a dictionary with required keys name and revision. Update tests to reflect this.
> TST: Change to correct model key format in tests

- src/fmu/dataio/dataio.py
- src/fmu/dataio/providers/_fmu.py
- tests/test_units/test_dataio.py
- tests/test_units/test_fmuprovider_class.py
PR to change from having `relization` as default `fmu_context,` to using environment variables from ERT to set the fmu_context value if not explicitly given. 
Closes #585
> ENH: Set fmu_context from env variables if not explicitly given

- src/fmu/dataio/dataio.py
- tests/test_units/test_dataio.py
PR to move deprecations present in ExportData init to the  `_show_deprecations_or_notimplemented` function. 
Also changed two `PendingDeprecationWarnings` to `UserWarnings` 
- Did consider `FutureWarning` but since the features already are deprecated and the argument has no effect, it felt more natural to give a `UserWarning`
> CLN: Collect deprecations in same function

- src/fmu/dataio/dataio.py
- src/fmu/dataio/providers/_fmu.py
- tests/test_units/test_fmuprovider_class.py
PR to move the validation of the workflow key outside of the `FmuProvider`, and utilizing existing pydantic model for the validation.
> CLN: Move validation of workflow key

- src/fmu/dataio/datastructure/configuration/global_configuration.py
PR to add the missing `description` field to `global_configuration.Model`.
The current implementation would just ignore the provided description information in the global_config file (if any).
> FIX: Add missing description to global_configuration.Model

- src/fmu/dataio/case.py
- src/fmu/dataio/datastructure/_internal/internal.py
PR to remove pydantic model `CaseMetadata` from datastructure internal to use the one for the schema `meta.FMUCase` .
They were identical except for  `meta.FMUCase` having:
- an optional description key
- uuid defined as type `UUID`
> CLN: Use FMUCase model from schema in CaseSchema

- src/fmu/dataio/_utils.py
- src/fmu/dataio/aggregation.py
- src/fmu/dataio/providers/_filedata.py
- tests/conftest.py
- tests/test_units/test_aggregated_surfaces.py
PR that fixes a bug in `AggregatedData` where data that requires extra info would fail in the pydantic validation.
Closes #597
Ideally I wanted to remove the Initialization of ExportData to extract metadata, and instead use more direct method calls to populate the necessary fields. I was not able to do that fully at this moment since the `objectdata_provider` takes an `ExportData` instance as argument.
This `AggregatedData` class would need some attention in the future. e.g. adding pydantic models for aggregated data, and adding more tests as all of our tests are only targeting the datatype surface.
> BUG: Handle content that requires extra info in AggregatedData

- src/fmu/dataio/_metadata.py
- src/fmu/dataio/_utils.py
- src/fmu/dataio/aggregation.py
- src/fmu/dataio/dataio.py
- src/fmu/dataio/datastructure/_internal/internal.py
- src/fmu/dataio/providers/_fmu.py
- tests/conftest.py
- tests/data/drogon/ertrun1/share/metadata/fmu_case.yml
- tests/test_units/test_fmuprovider_class.py
PR to use pydantic for metadata in the FmuProvider, and closes #572 and #577
Some additional refactoring of the FmuProvider was done
- make it more visible from the init what methods are setting the internal private properties.
- refactoring the logic for parsing folder information. Issue #557 will be addressed in an upcoming PR.
> CLN: Use pydantic in FmuProvider

- docs/preparations.rst
Solve #619 
SMDA has developed a dedicated feature for assembling necessary masterdata for FMU usage. This PR is synching the `fmu-dataio` documentation ("Get started"-section) with these recent changes.
Also did some other minor tweaks to the surrounding text.
> DOC: Synch Get Started docs with SMDA changes.

- src/fmu/dataio/_metadata.py
- src/fmu/dataio/dataio.py
- src/fmu/dataio/datastructure/configuration/global_configuration.py
- tests/conftest.py
- tests/test_units/test_dataio.py
- tests/test_units/test_global_configuration.py
- tests/test_units/test_metadata_class.py
PR that adds a two new arguments, `classification`  and `rep_include`, and deprecates the `ssdl_access` argument.
Kudos to @perolavsvendsen for describing the issue, and doing the groundwork in his PR https://github.com/equinor/fmu-dataio/pull/575
closes #601
closes #595
closes #540 
**Note:**
This PR does not solve the issue with state of classification being stored within the ExportData instance, and we should focus on #525 next to minimize the logic around classification.
> ENH: Add classification and rep_include argument

- src/fmu/dataio/aggregation.py
- src/fmu/dataio/dataio.py
- src/fmu/dataio/datastructure/_internal/internal.py
- src/fmu/dataio/datastructure/meta/enums.py
- src/fmu/dataio/providers/objectdata/_base.py
- tests/test_schema/test_pydantic_logic.py
- tests/test_units/test_contents.py
- tests/test_units/test_dataio.py
- tests/test_units/test_prerealization_surfaces.py
PR to refactor `AllowedContent`
- Change to doing most validation of `content` inside Pydantic
- Use the pydantic models for the schema for content that requires extra information inside `AllowedContent`.
- Get away from needing to keep `AllowedContent` and `ContentEnum` in sync
- Start requiring `content="seismic"` as dictionary with extra input - adresses #598
- keep deprecation warning for `content="property"` without extra info longer. Turned out that it is allowed in the schema.
> MAINT: Refactor AllowedContent

- src/fmu/dataio/dataio.py
- src/fmu/dataio/providers/_fmu.py
- tests/test_units/test_dataio.py
- tests/test_units/test_objectdataprovider_class.py
- tests/test_units/test_prerealization_surfaces.py
PR to collect the establishment of the `dataio._rootpath` in the ExportData initialization, to make it easier to understand how this important variable is set, and avoid overriding the state of the _roothpath later.
1. Use` ERT casepath` if in FMU context
2. Use` rms/model/../../.` if inside RMS and outside FMU
3. Use `pwd` if not inside RMS or running in FMU context
In order to do this it was needed to disallow updating `casepath` inside `export/generate_metadata`.
> MAINT: Simplify rootpath establishment

- src/fmu/dataio/dataio.py
- src/fmu/dataio/providers/_fmu.py
- tests/test_units/test_dataio.py
- tests/test_units/test_fmuprovider_class.py
#643 Introduced a breaking change where `casepath` was not allowed to be updated outside `ExportData` initialization.
This was a bit premature and caused Drogon to fail. We need to have a deprecation period for this before removing the option.
> REV: Support casepath argument outside of ExportData

- tests/conftest.py
- tests/test_units/test_objectdataprovider_class.py
- tests/test_units/test_prerealization_surfaces.py
- tests/test_units/test_rms_context.py
PR that closes #646  
(or at least tried to identify all **obvious** cases where inproper test setup occured 😄) 
Added some helper functions to be able to reset and set the ERT environment, to aid in the cases where we want to change this dynamically inside a test e.g. mocking running inside RMS interactively, and then running pre-sim workflow in ERT to re-export preprocessed data.
> TST: Fix inproper environment framework

- schema/definitions/0.8.0/examples/table_inplace.yml
- schema/definitions/0.8.0/examples/table_wellpicks.yml
- schema/definitions/0.8.0/schema/fmu_meta.json
- src/fmu/dataio/datastructure/meta/specification.py
- tests/test_units/test_metadata_class.py
Closes #650 by removing the `WellPointsDictionaryCaseSpecification`  pydantic model. 
Also, two issues were identified and fixed in the examples; tables requires fields `columns` and `size` .
> BUG: Fix data.spec not resolved properly by pydantic

- schema/definitions/0.8.0/schema/fmu_meta.json
- src/fmu/dataio/datastructure/meta/content.py
- src/fmu/dataio/providers/objectdata/_base.py
- src/fmu/dataio/providers/objectdata/_faultroom.py
- src/fmu/dataio/providers/objectdata/_provider.py
- src/fmu/dataio/providers/objectdata/_tables.py
- src/fmu/dataio/providers/objectdata/_xtgeo.py
- tests/test_units/test_objectdataprovider_class.py
Contributes to #564 
This also allows the getter to be optional in the cases in which the method will never be called because a bounding box is not relevant to the data type.
Schema was updated to reflect the added docstrings.
> ENH: Return BaseModel from bbox getters

- src/fmu/dataio/_metadata.py
- src/fmu/dataio/exceptions.py
- src/fmu/dataio/providers/_base.py
- src/fmu/dataio/providers/_filedata.py
- src/fmu/dataio/providers/_fmu.py
- tests/test_units/test_fmuprovider_class.py
Resolves #573 
Prefers to raise an exception over returning None from `get_metadata()` so that its return value is always valid metadata.
> ENH: Add Provider base class

- src/fmu/dataio/dataio.py
- src/fmu/dataio/providers/_fmu.py
- tests/test_units/test_fmuprovider_class.py
PR to remove the conversion of the `workflow` argument of type `str` to a `dict` inside the ExportData post-init, and do it more directly inside the `FmuProvider.`
Since we run the `_show_deprecations_or_notimplemented` twice, initially in the init and subsequently when running the  `generate_metadata` function (since users may have updated class arguments), it causes a `FutureWarning` to be thrown the second time saying that `workflow` of type `dict` is deprecated.
> MAINT: Move workflow conversion to silence warning

- src/fmu/dataio/_metadata.py
- src/fmu/dataio/providers/objectdata/_base.py
- tests/test_units/test_metadata_class.py
- tests/test_units/test_objectdataprovider_class.py
Resolves #564 
It now sets its state on initialization and returns a Pydantic model via the prescribed method. Does not do much of the possible clean-ups within the base class.
There is still more work to be within the object data provider base class but this should have the inputs (spec, bbox, etc) and outputs (content) where they need to be.
> ENH: Implement ObjectDataProvider as a Provider

- src/fmu/dataio/dataio.py
- src/fmu/dataio/providers/objectdata/_base.py
- tests/test_units/test_dataio.py
In the SIM2SEIS workflow in Drogon `unit` is given in as `None,` to avoid breaking changes for people we should support this.
> FIX: Support unit input as None

- src/fmu/dataio/__init__.py
- src/fmu/dataio/_metadata.py
- src/fmu/dataio/_utils.py
- src/fmu/dataio/dataio.py
- src/fmu/dataio/datastructure/_internal/internal.py
- src/fmu/dataio/preprocessed.py
- src/fmu/dataio/providers/_filedata.py
- src/fmu/dataio/providers/_fmu.py
- src/fmu/dataio/providers/objectdata/_base.py
- src/fmu/dataio/providers/objectdata/_provider.py
- tests/test_units/test_objectdataprovider_class.py
- tests/test_units/test_preprocessed.py
- tests/test_units/test_prerealization_surfaces.py
This PR adresses #593 and splits out all the logic of dealing with re-export of preprocessed data in a FMU run from `ExportData` to a new class `ExportPreprocessedData.` The re-export is mainly a copy process of the preprocessed data down to case level, but with an update of the fields `fmu`, `file` and `tracklog` in the metadata.
```python
surfacefilepath = "share/preprocessed/maps/my_surface.gri"
ExportPreprocessedData(config, casepath).export(surfacefilepath)
```
Note the initial export of these preprocessed data should still be handled by the `ExportData` class since it shares the same logic as exporting regular data, except that setting `fmu_context="preprocessed"` will ensure the data is exported and stored inside a `share/preprocessed` folder :
```python
exp = …
```
> MAINT: Split out preprocessed logic into separate class

- src/fmu/dataio/aggregation.py
- src/fmu/dataio/providers/objectdata/_base.py
- src/fmu/dataio/providers/objectdata/_faultroom.py
- src/fmu/dataio/providers/objectdata/_provider.py
- src/fmu/dataio/providers/objectdata/_tables.py
- src/fmu/dataio/providers/objectdata/_xtgeo.py
- src/fmu/dataio/types.py
- tests/test_units/test_filedataprovider_class.py
- tests/test_units/test_objectdataprovider_class.py
Starts on #666 😈
This PR tries to add some firmer standardization to how metadata is defined within objects we generate metadata for. Presently there are string literals defined and grouped into an unvalidated object returned from the child providers. This change makes progress toward having stronger guarantees that are also type checked.
This PR cleans up the base class and moves toward having these defined as properties of providers classes. To keep the PR from being too large it makes this change to the classname only.
This work precedes initialization internal metadata into a Pydantic object directly.
This PR should follow #660
> MAINT: Refactor ObjectDataProvider base class

- src/fmu/dataio/dataio.py
- tests/test_units/test_preprocessed.py
Fix bug to handle `casepath` given in as argument to `ExportData.export()`. 
As is the case in Drogon
https://github.com/equinor/fmu-drogon/blob/57007d8ac3faca2c743c5013a0756ea9ac52a7ec/ert/bin/scripts/wf_copy_preprocessed_dataio.py#L47-L53
Closes #675
> FIX: Support giving in arguments on export for preprocessed data

- schema/definitions/0.8.0/schema/fmu_meta.json
- src/fmu/dataio/case.py
- src/fmu/dataio/datastructure/_internal/internal.py
- src/fmu/dataio/datastructure/configuration/global_configuration.py
- src/fmu/dataio/datastructure/meta/meta.py
- tests/conftest.py
The `fmu.model.name` and `fmu.model.revision` should not be optional in the schema. Closes #684
> FIX: Require fmu.model info in schema

- src/fmu/dataio/_definitions.py
- src/fmu/dataio/aggregation.py
- src/fmu/dataio/providers/objectdata/_base.py
- src/fmu/dataio/providers/objectdata/_faultroom.py
- src/fmu/dataio/providers/objectdata/_provider.py
- src/fmu/dataio/providers/objectdata/_tables.py
- src/fmu/dataio/providers/objectdata/_xtgeo.py
- src/fmu/dataio/types.py
- tests/test_units/test_filedataprovider_class.py
- tests/test_units/test_objectdataprovider_class.py
> MAINT: Make format and extension provider properties

- src/fmu/dataio/dataio.py
- src/fmu/dataio/preprocessed.py
- src/fmu/dataio/providers/_fmu.py
- tests/test_units/test_fmuprovider_class.py
- tests/test_units/test_objectdataprovider_class.py
- tests/test_units/test_preprocessed.py
- tests/test_units/test_prerealization_surfaces.py
If model information is not provided to the `FMUProvider` it will use the model info found in the case metadata.
This change enables the removal of the `config` argument in the newly released `ExportPreprocessedData` class.
> ENH: Use fmu.model info from casemeta if not provided

- examples/s/d/nn/xcase/realization-0/iter-0/any/bin/export_grid3d.py
- schema/definitions/0.8.0/schema/fmu_meta.json
- src/fmu/dataio/_utils.py
- src/fmu/dataio/dataio.py
- src/fmu/dataio/datastructure/meta/content.py
- src/fmu/dataio/providers/_filedata.py
- src/fmu/dataio/providers/objectdata/_base.py
- src/fmu/dataio/providers/objectdata/_faultroom.py
- src/fmu/dataio/providers/objectdata/_provider.py
- src/fmu/dataio/providers/objectdata/_tables.py
- src/fmu/dataio/providers/objectdata/_xtgeo.py
- tests/test_units/test_rms_context.py
Ref. former PR https://github.com/equinor/fmu-dataio/pull/635 ...
A new attempt for adding the geometry field for a grid property. In this round, it is only relevant for grid properties, as a geometry link for e.g. a surface is more ambiguous.
Also, there was a former discussion on a new type of `uuid` made upfront by `fmu-dataio` in order to connect the geometry to a grid property. This PR does not include that; rather propose this (in case is still relevant) as a separate PR, since it has potential side effects and needs coordination with Sumo.
> ENH: Add optional geometry for Grid property

- src/fmu/dataio/dataio.py
- tests/test_units/test_dataio.py
- tests/test_units/test_ert_context.py
- tests/test_units/test_objectdataprovider_class.py
- tests/test_units/test_rms_context.py
`generate_metadata` stored the most recently generated metadata internally in the `ExportData` class. We don't need to do this, and probably don't want to do this, because an ExportData instance can be used to generate metadata across many objects.
> ENH: Don't persist metadata in ExportData

- src/fmu/dataio/preprocessed.py
Remove doc for unused `config` argument in  `ExportPreprocessedData`
> DOC: Remove unused config argument in ExportPreprocessedData

- src/fmu/dataio/_definitions.py
- src/fmu/dataio/_metadata.py
- src/fmu/dataio/aggregation.py
- src/fmu/dataio/dataio.py
- src/fmu/dataio/providers/_filedata.py
- tests/test_units/test_dataio.py
- tests/test_units/test_enum_classes.py
- tests/test_units/test_objectdataprovider_class.py
- tests/test_units/test_prerealization_surfaces.py
PR to deprecate `fmu_context="preprocessed"` and add a `preprocessed` argument instead
- getting very close to fixing this #544
- enables removing `fmu_context` arguments from all `ExportData` initializations, as it now is possible to use only ERT environment variables to infer the value of the context.
Closes #593
> DEP: Deprecate fmu_context='preprocessed'

- src/fmu/dataio/dataio.py
- tests/conftest.py
- tests/test_units/test_aggregated_surfaces.py
- tests/test_units/test_dataio.py
- tests/test_units/test_dictionary.py
- tests/test_units/test_ert_context.py
- tests/test_units/test_metadata_class.py
- tests/test_units/test_preprocessed.py
- tests/test_units/test_rms_context.py
- tests/test_units/test_table.py
PR to start emitting a deprecation warning for arguments coming in through kwargs in the `ExportData.generate_metadata()` and `ExportData.export()` methods.
Addresses #525
> DEP: Give deprecation warning for arguments in kwargs

- docs/src/conf.py
- docs/src/datamodel/index.rst
- schema/definitions/0.8.0/schema/fmu_meta.json
- src/fmu/dataio/case.py
- src/fmu/dataio/datastructure/_internal/internal.py
- src/fmu/dataio/datastructure/configuration/global_configuration.py
- src/fmu/dataio/datastructure/meta/meta.py
- src/fmu/dataio/providers/_fmu.py
- tests/conftest.py
Resolves #711 
Works on #696 
This PR suppresses the large number of warnings that were occurring when documentation was built as well as transfers some of the documentation that existed in `datamodel.rst` as docstrings.
Resolves #711 because the errors emitted will slowly disappear as more docstrings are added to the the items listed in every toctree page.
> DOC: Add more docstrings with some renaming

- docs/rms_oneliners.rst
- docs/src/conf.py
- docs/src/index.rst
- src/fmu/dataio/__init__.py
- src/fmu/dataio/export/rms/__init__.py
- src/fmu/dataio/export/rms/_conditional_rms_imports.py
- src/fmu/dataio/export/rms/volumetrics.py
- tests/conftest.py
- tests/test_export_rms/conftest.py
- tests/test_export_rms/test_export_rms_volumetrics.py
Proposal to add a one-liner for the volumetrics job in RMS
~~I choose to call a function; the alternative is to call a class with public methods. Not sure what is best.~~
~~Chose now this pattern: `RmsVolumetricsExport(...).export()`~~
Revert to function: `from fmu.dataio.export.rms import export_rms_volumetrics`
Will resolve #698
The tests are mocked and not optimal; see a need here to possibly do integration tests with RMS when that is possible.
> ENH: Add rms volumetrics wrapper

- pyproject.toml
- src/fmu/dataio/scripts/copy_preprocessed.py
- tests/test_integration/conftest.py
- tests/test_integration/test_hook_implementations.py
- tests/test_integration/test_wf_copy_preprocessed_data.py
PR that adds an ERT plugin workflow `WF_COPY_PREPROCESSED_DATAIO` to replace the use of the locally installed workflow showcased in Drogon:
- workflow job [ert/bin/jobs/WF_COPY_PREPROCESSED_DATAIO](https://github.com/equinor/fmu-drogon/blob/main/ert/bin/jobs/WF_COPY_PREPROCESSED_DATAIO)
- workflow script [ert/bin/scripts/wf_copy_preprocessed_dataio.py](https://github.com/equinor/fmu-drogon/blob/main/ert/bin/scripts/wf_copy_preprocessed_dataio.py)
- workflow file [ert/bin/workflows/xhook_copy_preprocessed_dataio](https://github.com/equinor/fmu-drogon/blob/main/ert/bin/workflows/xhook_copy_preprocessed_dataio)
Naming and arguments were kept the same as in Drogon to make this a drop-in replacement for the users that have implemented the Drogon workflow. 
Main differences with the Drogon …
> ENH: Add ERT WF to copy preprocessed data

- src/fmu/dataio/case.py
Working on issue number #693 
Remove redundant drop_nones from case.py
Aggregate.py doesn't fully use the pydandic model yet, so cannot be fully removed yet
> MAINT: Remove redundant drop_nones from case.py

- schema/definitions/0.8.0/schema/fmu_meta.json
- src/fmu/dataio/datastructure/_internal/internal.py
- src/fmu/dataio/datastructure/meta/content.py
- src/fmu/dataio/datastructure/meta/meta.py
- src/fmu/dataio/providers/objectdata/_base.py
> DOC: Add data/content docstrings

- schema/definitions/0.8.0/schema/fmu_meta.json
- src/fmu/dataio/aggregation.py
- src/fmu/dataio/dataio.py
- src/fmu/dataio/datastructure/_internal/internal.py
- src/fmu/dataio/datastructure/meta/content.py
- src/fmu/dataio/datastructure/meta/enums.py
- src/fmu/dataio/datastructure/meta/meta.py
- src/fmu/dataio/datastructure/meta/specification.py
- src/fmu/dataio/preprocessed.py
- src/fmu/dataio/providers/_filedata.py
- src/fmu/dataio/providers/_fmu.py
- src/fmu/dataio/providers/objectdata/_base.py
- src/fmu/dataio/providers/objectdata/_faultroom.py
- src/fmu/dataio/providers/objectdata/_provider.py
- src/fmu/dataio/providers/objectdata/_tables.py
- src/fmu/dataio/providers/objectdata/_xtgeo.py
- tests/test_units/test_dataio.py
- tests/test_units/test_fmuprovider_class.py
Resolves #696 
Also adds them to enums, and renames some classes to remove the redundant `Enum` in the name or align with other names (i.e. FMUSomething as opposed to FmuSomething).
Removing descriptions from the `Field(description="...")` also removes these descriptions from the schema right now. However, with Pydantic 2.7 (when we are able to upgrade to it), moving these descriptions to docstrings will add them back into the schema description. So this loss of fidelity is temporary.
> DOC: Complete adding docstrings to Pydantic models

- schema/definitions/0.8.0/schema/fmu_meta.json
- src/fmu/dataio/dataio.py
- src/fmu/dataio/datastructure/meta/content.py
- src/fmu/dataio/datastructure/meta/enums.py
- src/fmu/dataio/providers/objectdata/_base.py
- src/fmu/dataio/providers/objectdata/_provider.py
- tests/test_units/test_dataio.py
PR that closes #624.
Main problems were:
- `vertical_domain`  were hardcoded to `{"depth": "msl"}` where the dict value was the `depth_reference`
- the `depth_reference` was previously only possible to input for `content="depth"` (according to the schema)
I have been very much back and forth on how to best solve this one. But after discussions with @jcrivenaes we landed on adding a new general `domain_reference` argument in `ExportData` and as field in the schema as the best solution. This will be applicable both for time/depth domains. 
Other changes
- deprecate unused `depth_reference` argument in `ExportData` 
- support giving in `vertical_domain` as string ("time" or "depth") and deprecate dictionary input
- set  the `vertical_domain` according to the `content` if `content` is …
> FIX: Allow user input on vertical_domain

- src/fmu/dataio/_metadata.py
- src/fmu/dataio/dataio.py
- src/fmu/dataio/datastructure/meta/content.py
- src/fmu/dataio/datastructure/meta/meta.py
- src/fmu/dataio/providers/objectdata/_faultroom.py
- src/fmu/dataio/providers/objectdata/_tables.py
- src/fmu/dataio/providers/objectdata/_xtgeo.py
- src/fmu/dataio/types.py
Resolves #725 
Imports that are only used to annotate types in static type-checking, are moved into a type-checking block:
```python
if TYPE_CHECKING:
...
```
The block ensures that these imports will only be imported when we are doing static type checking with mypy.
NB! As stated in #725 imports that are used by Pydantic at runtime can not be moved to the TYPE_CHECKING block
> MAINT: Guard type checking imports in TYPE_CHECKING block

- tools/update_schema
Resolving #740 
Adds a new argument ```--force``` to the t**ools/update_schema** script that is used to update **fmu_meta.json** schema. 
This has been added to have a way to force an overwrite of the current json schema, if the current json schema has been malformed for some reason, e.g. because of a merge conflict.
**Changes :** 
1. ```--force``` has been added as a new valid argument to the script
2. When running the script with the ```--force``` argument, the script will skip checking/validating the current schema and overwrite with the new one. 
2. In case of a json parsing error of the current json schema, the script will exit and inform the user about the possibility of running the script with the ```--force``` argument. 
**Local testing**
The changes has been testes locally by:
1. …
> ENH: Add --force option to script tools/update_schema

- src/fmu/dataio/__init__.py
- src/fmu/dataio/case.py
- src/fmu/dataio/dataio.py
- src/fmu/dataio/providers/_fmu.py
- src/fmu/dataio/scripts/create_case_metadata.py
- tests/test_units/test_fmuprovider_class.py
- tests/test_units/test_initialize_case.py
Resolves #171 
The class ```InitializeCase``` in ```fmu/datio/case.py``` has been renamed to ```CreateCaseMetadata```. This has been done to be more precise on what is actual created in the code in fmu-datio, and to avoid confusion as case initialization is something that is done in ERT.
Tests has also been renamed to match the new name of the class.
> MAINT: Rename 'InitialCase" class to 'CreateCaseMetadata'

- examples/s/d/nn/_project/aggregate_surfaces.py
- src/fmu/dataio/_utils.py
- src/fmu/dataio/aggregation.py
- tests/test_units/test_aggregated_surfaces.py
Resolves #730 and #693 
Now using Pydantic models in aggregation.py to validate metadata. In addition, the following refactoring and changes has been made:
- The internal method `_generate_aggrd_metadata` has been renamed to `_set_metadata`
- Remove the method `filter_validate_metadata` in `_utils` as validation will be taken care of by Pydantic
- If the validation of the metadata with the Pydantic models fail, we raise an exception
- We do the model_dump only when the metadata is returned. The internal metadata object will be stored as a Pydantic base model
- The input parameter `skip_null` has been deprecated and will always be set to True. A deprecation warning will be raised if it is being used. 
Tests have been updated/fixed to match the new changes and use the correct types as …
> ENH: Use Pydantic models to validate metadata in aggregation.py and remove drop_nones

- src/fmu/dataio/_utils.py
Resolves #693 
Removed the function `drop_nones()` from the utils models which is no longer being used now that we are utilizing validation from the Pydantic model.
> MAINT: Remove drop nones function from utils module

- schema/definitions/0.8.0/schema/fmu_meta.json
- src/fmu/dataio/_metadata.py
- src/fmu/dataio/_model/enums.py
- src/fmu/dataio/_model/fields.py
- src/fmu/dataio/preprocessed.py
- tests/test_units/test_metadata_class.py
Resolves first task in #662 
Create an enum `TracelogEventTypes` for the three valid event types of the `TracklogEvent` module: 
* `created`
* `updated`
*  or `merged`
and use that as the type for the field `event`.
> ENH: Create enum for tracklog event type

- schema/definitions/0.8.0/schema/fmu_meta.json
- src/fmu/dataio/_metadata.py
- src/fmu/dataio/_model/fields.py
- src/fmu/dataio/_model/internal.py
- src/fmu/dataio/_model/root.py
- src/fmu/dataio/aggregation.py
- src/fmu/dataio/case.py
- src/fmu/dataio/preprocessed.py
- tests/test_units/test_metadata_class.py
Resolves #662 
Represent the metadata tracklog as a Pydantic RootModel with the name `Tracklog`.
A new class `Tracklog` has been created which inherits the Pydantic class `RootModel`. The new class `Tracklock` encapsulates:
* The list of tracklog events as the root property of the `RootModel`
* Functionality for constructing a tracklog and adding new records to it. 
* Dunder methods `__getitem__` and `__iter__` for getting and iterate over the items of the list in the `RootModel`
Tests have been updated accordingly.
> ENH: Represent the metadata tracklog as a Pydantic RootModel `Tracklog`

- src/fmu/dataio/_metadata.py
- src/fmu/dataio/_model/schema.py
- src/fmu/dataio/aggregation.py
- src/fmu/dataio/case.py
- src/fmu/dataio/preprocessed.py
- src/fmu/dataio/providers/_fmu.py
- src/fmu/dataio/providers/objectdata/_base.py
Resolves #728 
Update the naming convension for internal data structures. The following changes have been made:
* The file "internal.py" containing internal data structures has been renamed to "schema.py"
* The datastructures defined in "schema.py" has been renamed and the "Internal" prefix has been added in this way:
* DataClassMeta -> InternalObjectMetadata
* CaseSchema -> InternalCaseMetadata
* FMUClassMetaData -> InternalFMU
* UnsetAnyContent -> InternalAnyData
* UnsetContent -> InternalUnsetData
* The class FMUModelCase has been deleted as and replaced by the class FMUBase.
> MAINT: Update naming convension for internal data structures

- pyproject.toml
Pin package of `pyarrow-stubs` to version `10.0.1.9` as we are waiting for the latest version to be stable. 
There seems to be an issue in the latest release of `pyarrow-stubs` that is causing the mypy check of the CI to fail.
Have pinned the version to version "10.0.1.9" now until the latest version is stable.
> BLD: Pin package pyarrow-stubs to version 10.0.1.9

- src/fmu/dataio/_model/fields.py
- src/fmu/dataio/_model/global_configuration.py
- tests/test_units/test_dunder_methods.py
> ENH: Add dunder accessors to Pydantic RootModels

- src/fmu/dataio/_model/global_configuration.py
- tests/test_units/test_dataio.py
Resolves #775 
Also added deprecation warnings so that we in the future can get rid of the entire `field_validator` here
> FIX: Do not convert alias as string to list of characters

- src/fmu/dataio/_model/global_configuration.py
- src/fmu/dataio/providers/objectdata/_base.py
- tests/test_units/test_dataio.py
- tests/test_units/test_objectdataprovider_class.py
Resolves #772
The `top/base/offset` information was dropped after roundtripping with pydantic since these fields were not defined in the `GlobalConfigurationModel`.
Also removed the `NamedStratigraphy` dataclass, as it is obsolete and can be replaced by the `global_configuration.StratigraphyElement`
> BUG: Preserve top/base/offset information from config

- src/fmu/dataio/_model/global_configuration.py
- tests/conftest.py
Replace duplicate pydantic `global_configuration.Asset` with `fields.Asset`
> MAINT: Replace global_configuration.Asset with fields.Asset

- docs/src/example_surface.yml
- docs/src/example_surface_v070.yml
- docs/src/preparations.rst
- examples/s/d/nn/xcase/realization-0/iter-0/fmuconfig/output/global_variables.yml
- examples/s/d/nn/xcase/realization-1/iter-0/fmuconfig/output/global_variables.yml
- examples/s/d/nn/xcase/realization-9/iter-0/fmuconfig/output/global_variables.yml
- examples/s/d/nn/xcase/share/metadata/fmu_case.yml
- schema/definitions/0.8.0/examples/aggregated_surface_depth.yml
- schema/definitions/0.8.0/examples/case.yml
- schema/definitions/0.8.0/examples/dictionary_parameters.yml
- schema/definitions/0.8.0/examples/polygons_field_outline.yml
- schema/definitions/0.8.0/examples/polygons_field_region.yml
- schema/definitions/0.8.0/examples/preprocessed_surface_depth.yml
- schema/definitions/0.8.0/examples/summary_table.yml
- schema/definitions/0.8.0/examples/surface_depth.yml
- schema/definitions/0.8.0/examples/surface_faultroom_data.yml
- schema/definitions/0.8.0/examples/surface_fluid_contact.yml
- schema/definitions/0.8.0/examples/surface_seismic_amplitude.yml
- schema/definitions/0.8.0/examples/table_inplace.yml
- schema/definitions/0.8.0/examples/table_wellpicks.yml
- schema/definitions/0.8.0/schema/fmu_results.json
- src/fmu/dataio/_model/fields.py
- src/fmu/dataio/_utils.py
- src/fmu/dataio/case.py
- src/fmu/dataio/providers/_fmu.py
- tests/conftest.py
- tests/data/drogon/ertrun1/share/metadata/fmu_case.yml
- tests/data/drogon/ertrun1_no_iter/share/metadata/fmu_case.yml
- tests/data/drogon/global_config2/global_variables.yml
- tests/data/drogon/global_config2/global_variables_norw_letters.yml
> ENH: Validate uuids against pydantic.UUID4 (#759)

- pyproject.toml
Resolves #770 
Unpin pyarrow-stubs package version.
In PR https://github.com/equinor/fmu-dataio/pull/769 the version of 'pyarrow-subs' was pinned to version 10.0.1.9 as the latest version was not stable. A new stable version has now been released and hence the package version has been unpinned.
> MAINT: Unpin pyarrow-stubs package version

- docs/src/dataio_3_migration.rst
- src/fmu/dataio/_model/schema.py
- tests/test_units/test_dataio.py
PR to change to a deprecation warning for `content=None` and document it in the migration guide.
> DEP: Change to deprecation warning for content not provided

- schema/definitions/0.8.0/examples/summary_table.yml
- schema/definitions/0.8.0/examples/table_inplace.yml
- schema/definitions/0.8.0/examples/table_wellpicks.yml
- schema/definitions/0.8.0/schema/fmu_results.json
- src/fmu/dataio/_model/specification.py
- src/fmu/dataio/providers/objectdata/_tables.py
- tests/test_units/test_ert_context.py
- tests/test_units/test_table.py
> ENH: Add `num_columns`, `num_rows` to table spec

- schema/app/install-schema-files.sh
PR to remove `fmu_meta.json` from radix now that sumo has switched back to `fmu_results.json`
Closes #760
> MAINT: Remove fmu_meta.json from radix container

- docs/src/dataio_3_migration.rst
- src/fmu/dataio/_utils.py
- src/fmu/dataio/dataio.py
- tests/test_units/test_dataio.py
- tests/test_units/test_preprocessed.py
Closes #602 
- Added a new function to get the export path of an object without having to fetch it from the metadata. This is used when invoking the `export` function and the config is not valid (i.e. no metadata should be exported)
- Added deprecation warning for the `generate_metadata` function saying in the future no metadata will be returned if the config is invalid
- once the deprecation period has ended we can remove checks of the validity of the config inside the `generate_export_metadata,` and remove `masterdata` and `access` as optional fields in the pydantic model used to generate metadata.
> ENH: Do not call generate_metadata() on export when config is not valid

- docs/src/rms_oneliners.rst
- src/fmu/dataio/export/_decorators.py
- src/fmu/dataio/export/rms/__init__.py
- src/fmu/dataio/export/rms/volumetrics.py
- tests/test_export_rms/test_export_rms_volumetrics.py
Rename name of one-liner function before it comes into production, cf #795
The RMS context is already evident as 
`from fmu.dataio.export.rms import export_volumetrics`
I also added a commit that marks this function as experimental (a bit out of sync, but we do not expect any current users)
> FIX, DEP: rename from export_rms_volumetrics to export_volumetrics

- schema/definitions/0.8.0/schema/fmu_results.json
- src/fmu/dataio/_model/data.py
- src/fmu/dataio/_model/specification.py
Resolves #814 
Resolves #815 
I still have a bit uncertainty about some fields. In some cases we give optional lists a default value of an empty list, in some cases it's `null`.
A few instances I added the `Field` or sorted the keyword arguments to it to make the default show first.
I'm working on a test that will run through all the models and fail if an optional doesn't provide a default value... but figured I can put this up before that is working.
> FIX: Give Optionals a default value

- src/fmu/dataio/_model/schema.py
- src/fmu/dataio/providers/objectdata/_base.py
> MAINT: Fix pydantic serialization warning

- .github/workflows/fmudataio-documention.yml
- docs/src/datamodel/index.rst
> Fix doc link and parallelize doc build

- src/fmu/dataio/providers/_fmu.py
- tests/test_units/test_fmuprovider_class.py
> ENH: Support restart cases with no iteration folder

- pyproject.toml
The `sphinx-rtd-theme 3.0.0` causes documentation build to fail #836 
Not sure why yet, but to get tests to pass we should pin the version while investigating.
> BLD: Pin sphinx-rtd-theme<3.0.0

- schema/definitions/0.8.0/schema/fmu_results.json
- src/fmu/dataio/_model/data.py
- tests/test_units/test_contents.py
Closes #833 and re-enables support for content="transmissibilities"
> FIX: Add back support for content='transmissibilities'

- schema/definitions/0.8.0/schema/fmu_results.json
- src/fmu/dataio/_model/fields.py
- src/fmu/dataio/_model/root.py
> ENH: Add fmu.realization.is_reference to schema

- schema/definitions/0.8.0/schema/fmu_results.json
- src/fmu/dataio/_model/fields.py
PR to set `file.checksum_md5` non optional. It was non optional in the legacy schema, and was introduced in https://github.com/equinor/fmu-dataio/pull/512/files, probably by mistake.
Closes #835
> FIX: Set file.checksum_md5 non optional

- tests/test_schema/test_pydantic_logic.py
This PR addresses #819 and adds a test to check 
- all models in `AnyData` have a `content` attribute 
- the annotation of the `content` attribute is a `Literal` with one `enum.Content` value
- all enums in `Content` is represented by a pydantic model in `AnyData.` 
- the number of models in `AnyData` match the number of enums in `Content`
relevant problem encountered recently ref #833
This PR is based on #834,  which is awaiting #835 to be solved.
Will rebase this one when ☝️ is solved. 😄
> TST: Test that all content enums are represented in AnyData

- docs/src/dataio_3_migration.rst
- src/fmu/dataio/aggregation.py
PR that changes to always calculate an MD5 sum for aggregated objects.
This was recently done for exports through `ExportData` in #844
Addresses #842
> DEP: Always compute md5 for aggregated objects

- src/fmu/dataio/_utils.py
- src/fmu/dataio/aggregation.py
- src/fmu/dataio/dataio.py
- src/fmu/dataio/providers/_filedata.py
- tests/test_units/test_checksum_md5.py
PR that adds relevant functionality and changes from calculating MD5 hashes from file stream to memory stream when  populating the `checksum_md5` field _if possible._ 
For objects that do not support writing to memory streams they will still be written to temporary file before computing MD5, for dataio supported datatypes this applies to the `xtgeo.Cube` on `SEGY` format.
Improves performance by dropping the need for doing a temporary export the object to disk in order to get the MD5 sum.
Closes #552
> ENH: Calculate hashes in memory

- src/fmu/dataio/hook_implementations/jobs.py
- src/fmu/dataio/scripts/copy_preprocessed.py
- src/fmu/dataio/scripts/create_case_metadata.py
- tests/test_integration/test_hook_implementations.py
> Switch to Erts newer plugin system

- docs/src/dataio_3_migration.rst
- src/fmu/dataio/_utils.py
- src/fmu/dataio/aggregation.py
- src/fmu/dataio/case.py
- src/fmu/dataio/dataio.py
- src/fmu/dataio/preprocessed.py
- tests/test_units/test_dataio.py
- tests/test_units/test_preprocessed.py
- tests/test_units/test_utils.py
Closes #857 
The functionality has never worked and could be removed. I kept the class variables for now, just in case anyone has them in their script, and added warning if anyone uses them
> DEP: Writing metadata on json format

- schema/definitions/0.8.0/schema/fmu_results.json
- src/fmu/dataio/_model/specification.py
- src/fmu/dataio/providers/objectdata/_xtgeo.py
- tests/test_units/test_rms_context.py
PR to add a `data.spec.zonation` entry for `xtgeo.Grid` objects.
- utilizes the `xtgeo.Grid.subgrids` functionality and sets zonation if subgrids are set
- The zonation list are ordered on shallowest to deepest zone.  
Format was landed after discussion with webviz developers on suitable format
closes #860 
related #782
> ENH: Add zonation with layer range info to grid metadata

- schema/definitions/0.8.0/schema/fmu_results.json
- src/fmu/dataio/_model/enums.py
- src/fmu/dataio/_model/fields.py
- src/fmu/dataio/providers/_fmu.py
- tests/conftest.py
- tests/data/snakeoil/export-a-surface
- tests/test_integration/conftest.py
- tests/test_integration/ert_config_utils.py
- tests/test_integration/test_simple_export_run.py
- tests/test_integration/test_wf_copy_preprocessed_data.py
- tests/test_integration/test_wf_create_case_metadata.py
- tests/test_units/test_dataio.py
- tests/test_units/test_fmuprovider_class.py
Resolves #804 
Resolves #690 (more or less)
Resolves #263 
The simulation mode should allow contextual inference about the type of ensemble this data is derived from.
- Marked resolving #690 since it produces metadata from an ert run then validates that metadata against the model
- Marked resolving #263 for the above, and because we now have integration tests with ert against the two workflows and a simple case that can be expanded upon more easily
> ENH: Add ert simulation mode to object metadata

- pyproject.toml
Pydantic version 2.10 was released november 20th. 
This lead to issues for ERT for which they had to pin the Pydantic version < 2.10.
To not be in conflict with this, we also pin the `pydantic` version in `fmu-dataio` < `2.10`.
Once https://github.com/equinor/ert/issues/9292 has bee resolved, we should also unpin `fmu-dataio`. This will be followed up through https://github.com/equinor/fmu-dataio/issues/874
> BLD: Pin pydantic to < 2.10 as ERT have done

- docs/src/rms_oneliners.rst
> FIX: Update documentation for export_inplace_volumes

- .github/workflows/fmudataio-publish-pypi.yml
- .github/workflows/linting.yml
- .github/workflows/mypy.yml
Resolves #898 
We are moving to Python 3.11 being our current version. May as well do that here too.
> CI: Run most actions with Python 3.11

- schema/definitions/0.8.0/schema/fmu_results.json
- src/fmu/dataio/_definitions.py
- src/fmu/dataio/_model/data.py
- src/fmu/dataio/_model/enums.py
- tests/conftest.py
- tests/test_units/test_contents.py
- tests/test_units/test_table.py
Resolves #689 
Rationale for new content type: 'simulationtimeseries' is more of a super-type of 'timeseries' than a subtype since it can contain multiple timeseries vectors.
> ENH: Add 'simulationtimeseries' content type

- pyproject.toml
- src/fmu/dataio/_definitions.py
- src/fmu/dataio/providers/objectdata/_tables.py
- tests/conftest.py
- tests/test_units/test_table.py
#901 suggests a better and more structured approach to handle table indexes later. The current implementation of giving standard table index columns does not actually seem strictly tied to the content type and could add duplicated columns if it saw a match.
It could also possibly be handled from within the ObjectDataProvider.
> FIX: Re-add 'timeseries' index without duplication

- tests/test_export_rms/test_export_rms_volumetrics.py
For testing functionaliy related to `_ExportVolumetricsRMS` we have to duplicate a lot of code in every test in order to have a mock of the rmsapi modules and mocking the return value of the `_get_table_with_volumes` function to avoid the instance creation failing.
This PR gathers this into a fixture that can be used in the tests instead. This will be useful as the tests for this class are still being added.
> TST: Add exportvolumetrics fixture

- src/fmu/dataio/export/rms/inplace_volumes.py
- tests/test_export_rms/test_export_rms_volumetrics.py
PR that sets `BULK`, `PORV`, `HCPV` as required in addition to and `STOIIP/GIIP` depending on what fluid has been selected.
It is done by validating the final table before export.
Closes #900
> ENH: Add required volume calculations

- pyproject.toml
- src/fmu/dataio/_products/inplace_volumes.py
- tests/test_export_rms/test_export_rms_volumetrics.py
Resolves #877 
This will need refinement and discussion, but here is something to discuss.
- Suggests a module interface from `_products`
- When FMU products are exported they can import the VERSION and SCHEMA to use:
- ```yml
data:
product:
type: ...
file_schema:
version: {fmu.dataio._products.inplace_volumes.VERSION}  # Or schema_version? Not needed?
url: {fmu.dataio._products.inplace_volumes.SCHEMA} 
```
- This should give consumers approximately what they need for data consistency guarantees
- The bad: most things are optional. Currently a valid product can look like:
- `ZONE,REGION,BULK_TOTAL,PORV_TOTAL`
- This isn't very useful -- it is a poor data contract to make (and the last two may need to be optional too?)
- This doesn't yet set-up the deployment of the schema, a way to …
> ENH: Add inplace volumes result and schema

- src/fmu/dataio/_utils.py
- src/fmu/dataio/export/rms/inplace_volumes.py
- src/fmu/dataio/providers/objectdata/_provider.py
- tests/test_export_rms/test_export_rms_volumetrics.py
Resolves #923 
Also moved all lazy pyarrow imports to non-lazy. At some point the lazy imports will cause confusion or error.
> ENH: Export inplace volumes table as parquet

- schema/definitions/0.8.0/schema/fmu_results.json
- src/fmu/dataio/_model/root.py
- tests/test_schema/test_schema_uptodate.py
> FIX: Remove AnyProduct discriminator mapping

- src/fmu/dataio/export/rms/inplace_volumes.py
- tests/test_export_rms/test_export_rms_volumetrics.py
Resolves #896 
Fixed a semi-bug with setting the dataframe FLUID column as well.
> ENH: validate inplace volumes with Pydantic

- schema/definitions/0.8.0/schema/fmu_results.json
- src/fmu/dataio/_definitions.py
- src/fmu/dataio/_metadata.py
- src/fmu/dataio/_model/root.py
- src/fmu/dataio/_model/schema.py
- tests/test_units/test_metadata_class.py
- tools/update_schema
Resolves #909 
Opens #907
A little pre-work for setting up the inplace volumes product schema checking + schema versioning
> MAINT: Template schema version and add dev schema url

- .github/workflows/ci-fmudataio.yml
- Dockerfile
This reverts the docker `chown` back to the workdir without specifying the schemas dir directly, which was incorrect to do. It also adds a CI job to check that it builds.
> FIX: Revert Dockerfile chown

- Dockerfile
Also uses USER 101, docker's unprivileged user id, over adding a new user to accomplish the same
> FIX: Copy docker files correctly

- src/fmu/dataio/_products/inplace_volumes.py
- src/fmu/dataio/export/_enums.py
- src/fmu/dataio/export/rms/inplace_volumes.py
- tests/test_export_rms/test_export_rms_volumetrics.py
> ENH: Set Region required in inplace_volumes

- src/fmu/dataio/export/_enums.py
- src/fmu/dataio/export/rms/inplace_volumes.py
- tests/test_export_rms/test_export_rms_volumetrics.py
No need to treat the `FLUID_COLUMN` separate anymore after we got the enums in `InplaceVolumes` in place.
> MAINT: Drop separate FLUID_COLUMN variable

- src/fmu/dataio/providers/objectdata/_faultroom.py
- src/fmu/dataio/providers/objectdata/_utils.py
- tests/conftest.py
- tests/test_units/test_checksum_md5.py
- tests/test_units/test_objectdataprovider_class.py
- tests/test_units/test_providers_utils_class.py
Resolves #724, and sorts the mapped names according to the given stratigraphic column.
Discussion on Slack: https://equinor.slack.com/archives/C06E3UTGTEV/p1719922723901579
> ENH: Faultroom export - add mapping of juxt.pos. to SMDA names (#724)

- .github/workflows/ci-fmudataio.yml
- docs/ext/pydantic_autosummary/generate.py
- examples/s/d/nn/xcase/realization-0/iter-0/any/bin/export_grid3d.py
- examples/s/d/nn/xcase/realization-0/iter-0/rms/bin/export_a_surface.py
- examples/s/d/nn/xcase/realization-0/iter-0/rms/bin/export_faultpolygons.py
- examples/s/d/nn/xcase/realization-0/iter-0/rms/bin/export_faultroom_surfaces.py
- examples/s/d/nn/xcase/realization-0/iter-0/rms/bin/export_propmaps.py
- examples/s/d/nn/xcase/realization-1/iter-0/rms/bin/export_a_surface.py
- examples/s/d/nn/xcase/realization-9/iter-0/rms/bin/export_a_surface.py
- pyproject.toml
- src/fmu/dataio/aggregation.py
- src/fmu/dataio/export/rms/_conditional_rms_imports.py
- src/fmu/dataio/providers/objectdata/_base.py
- tests/test_export_rms/test_export_rms_volumetrics.py
- tests/test_integration/test_wf_copy_preprocessed_data.py
- tests/test_units/test_aggregated_surfaces.py
- tests/test_units/test_checksum_md5.py
- tests/test_units/test_dataio.py
- tests/test_units/test_dunder_methods.py
- tests/test_units/test_ert_context.py
- tests/test_units/test_fmuprovider_class.py
- tests/test_units/test_objectdataprovider_class.py
- tests/test_units/test_preprocessed.py
- tests/test_units/test_prerealization_surfaces.py
- tests/test_units/test_rms_context.py
- tests/test_units/test_utils.py
This implements some additional linting rules and prepares a few others. It also adds the `--cov --cov-report term-missing` coverage report to be emitted at the end of test runs, which may be noisier but still useful to see. The test runs install the package with `-e` now so that the code lines missing test coverage are visible.
> STY: Apply more linting rules

- pyproject.toml
- src/fmu/dataio/_utils.py
- src/fmu/dataio/export/rms/inplace_volumes.py
- src/fmu/dataio/providers/_filedata.py
A few more tiny ones, with some added ignores/config.
> STY: ruff check pandas, pyupgrade

- src/fmu/dataio/_metadata.py
- src/fmu/dataio/dataio.py
- src/fmu/dataio/export/rms/inplace_volumes.py
- src/fmu/dataio/providers/objectdata/_base.py
- src/fmu/dataio/providers/objectdata/_provider.py
- tests/test_export_rms/test_export_rms_volumetrics.py
- tests/test_units/test_dataio.py
Final PR to start adding `data.product` to the metadata for `inplace_volumes.`
Added separate private export function in `ExportData` to be used for export of data that qualifies as products. Using this export function will add product information to the exported metadata.
> ENH: Add product to exported metadata for inplace_volumes

- src/fmu/dataio/_metadata.py
- src/fmu/dataio/_model/schema.py
- src/fmu/dataio/providers/_fmu.py
I might be crazy but I think this no longer needed
> MAINT: Remove now redundant InternalFMU

- .github/workflows/schemas-up-to-date.yml
- src/fmu/dataio/_definitions.py
- tools/update-schema
Resolves #907 
Stacked on #957 
This will cause the schemas to overwrite with an updated $id field, but
only if nothing else has changed. It is also tested in GitHub Actions.
See https://github.com/equinor/fmu-dataio/actions/runs/12671501765/job/35313394311?pr=960#step:6:13 for how this looks when trying to merge a non-release version of the schema into the staging branch.
When preparing a PR for the release branch, you just need to run `SCHEMA_RELEASE=1 ./tools/update-schema`
> ENH: Add release logic to 'update-schema' 

- schemas/0.8.0/fmu_results.json
- src/fmu/dataio/_metadata.py
- src/fmu/dataio/_model/root.py
- src/fmu/dataio/aggregation.py
- src/fmu/dataio/case.py
- src/fmu/dataio/preprocessed.py
- src/fmu/dataio/providers/_fmu.py
- src/fmu/dataio/providers/objectdata/_base.py
- src/fmu/dataio/providers/objectdata/_export_models.py
- tools/update-schema
This restructures how these classes are formed and where they live. It was confusing to locate them with the model when they are really just tweaks to the model for us when exporting. This refactor tries to bring some clarity to that relationship.
It also changes some of the metadata classes to use their literal values as defaults which changed the schema.
> MAINT: Refactor 'schema'/'internal' classes 

- schemas/0.8.0/fmu_results.json
- src/fmu/dataio/_metadata.py
- src/fmu/dataio/_models/fmu_results/fmu_results.py
- tests/test_units/test_metadata_class.py
Closes #969 
Change so that the `$schema` field (the schema url) is added to the `MetadataBase` used in the `FmuResults` model, instead of directly into the `ObjectMatadataExport` and `CaseMetadataExport.`
This change will add the definition of this field into the schema.
> MAINT: Define schema inside FmuResults model

- src/fmu/dataio/_definitions.py
- tests/conftest.py
- tests/test_units/test_table.py
Added `FLUID` as standard table index column, and fixed typo in `LICENSE` for tables of content `volumes`.
Closes #918 
Closes #917
> FIX: Fix standard table index for volumes

- src/fmu/dataio/_definitions.py
- tests/conftest.py
- tests/test_units/test_table.py
PR to add `SATNUM` as standard table index column for tables of content `relperm`
Closes #931 
number 1000 🍾 🎊 🎉
> ENH: Add standard table index column for `relperm`

- src/fmu/dataio/_definitions.py
- src/fmu/dataio/dataio.py
- src/fmu/dataio/exceptions.py
- src/fmu/dataio/providers/objectdata/_base.py
- tests/test_units/test_objectdataprovider_class.py
Small PR to move custom exceptions defined in `fmu.dataio._definitions` to the already existing `fmu.dataio.exceptions`
> MAINT: Move exceptions from _definitions to exceptions file

- src/fmu/dataio/_definitions.py
- src/fmu/dataio/providers/objectdata/_tables.py
- tests/test_units/test_table.py
PR to add a way to separate which index columns are required and not. 
On the road to improving data standards we would like to give the users information when they are not following the standards, this enables giving the warning only for columns marked as required. 
Closes #1011 
Towards #915
> MAINT: Add extra required info for standard_table_index

- pyproject.toml
PR to pin Sphinx==8.1.3
New version of sphinx released yesterday causes CI to fail #1017 
Not sure why yet, will make an issue to unpin it once we do.
> CI: Pin Sphinx==8.1.3

- docs/src/dataio_3_migration.rst
- src/fmu/dataio/dataio.py
- src/fmu/dataio/providers/objectdata/_base.py
- src/fmu/dataio/providers/objectdata/_export_models.py
- tests/test_units/test_contents.py
- tests/test_units/test_dataio.py
PR to start deprecating `content` as a dictionary, and introduce a new `content_metadata` argument for the additional information. 
Closes #1012  
Closes #1005
> DEP: Deprecate content as dict input, split in two arguments

- src/fmu/dataio/providers/objectdata/_base.py
- tests/test_units/test_dataio.py
Add warning to inform user if `content_metadata` is not required as input.
Closes #1025
> MAINT: Add warning if content_metadata is not required

- docs/src/dataio_3_migration.rst
- src/fmu/dataio/providers/objectdata/_tables.py
- tests/test_export_rms/test_export_rms_volumetrics.py
- tests/test_units/test_table.py
PR to start using the `content` to find the correct standard `table_index` columns for a table if it is defined in the `STANDARD_TABLE_INDEX_COLUMNS`.
Previous functionality has been to compare the columns in the table against all commonly known index columns (independent of content), and set the table_index based on matches found.
- This functionality is kept for contents that don't yet have standard table_index columns defined, but is deprecated with a message telling the user to set the table_index as input to prevent `data.table_index` being empty in the future. 
Closes #915
> FIX: Use content to find correct standard table_index for tables

- src/fmu/dataio/dataio.py
- tests/test_export_rms/test_export_rms_volumetrics.py
- tests/test_units/test_dataio.py
Add requirement that the config should be valid when exporting `standard_results` to prevent generating invalid metadata.
Closes #1023
> FIX: Require a valid config for standard_result exports

- schemas/0.9.0/fmu_results.json
- src/fmu/dataio/_models/fmu_results/specification.py
Adresses #911
Added stricter validation to specification model fields where applicable for schema `0.9.0` 
- Ensuring relevant fields are greater or equal to 0  
- removing `num_columns` and `num_rows` as optional for TableSpecification, it is always set.
> ENH: Stricter validation for specification fields

- schemas/0.9.0/fmu_results.json
- src/fmu/dataio/_models/fmu_results/data.py
- src/fmu/dataio/_models/fmu_results/fields.py
- src/fmu/dataio/providers/_fmu.py
- tests/test_units/test_dunder_methods.py
Adresses #911 
PR with updates to the `0.9.0` schema version:
1. Remove fields no longer populated by `fmu-dataio:`
- `data.stratigraphic_alias`
- `fmu.realization.parameters`
- `fmu.realization.jobs`
- `fmu.aggregation.parameters`
- `file.relative_path_symlink`
- `file.absolute_path_symlink`
2. Make some fields required, most of them are within an optional block and does not have to be optional themselves.
3. Validate that `fmu.realization.id` and `fmu.iteration.id` are always greater or equal to 0.
No tests necessary for these schema changes.
> ENH: Schema 0.9.0 updates

- examples/0.8.0/summary_table.yml
- schemas/0.9.0/fmu_results.json
- src/fmu/dataio/_models/fmu_results/data.py
- src/fmu/dataio/_models/fmu_results/enums.py
- src/fmu/dataio/providers/objectdata/_base.py
- src/fmu/dataio/providers/objectdata/_faultroom.py
- src/fmu/dataio/providers/objectdata/_provider.py
- src/fmu/dataio/providers/objectdata/_tables.py
- src/fmu/dataio/providers/objectdata/_xtgeo.py
Towards #911 
Added a `FileFormat` enum to strengthen the validation of the `data.format` field.
The enum values are a combination of supported export formats from `fmu-dataio` and formats found in the `fmu-sumo-uploader` and `fmu-sumo-aggregation-service`.
Existing tests should be sufficient.
> MAINT: Add FileFormat enum to schema

- src/fmu/dataio/_utils.py
- src/fmu/dataio/aggregation.py
- src/fmu/dataio/dataio.py
- src/fmu/dataio/providers/_filedata.py
- src/fmu/dataio/providers/objectdata/_base.py
- src/fmu/dataio/providers/objectdata/_faultroom.py
- src/fmu/dataio/providers/objectdata/_provider.py
- src/fmu/dataio/providers/objectdata/_tables.py
- src/fmu/dataio/providers/objectdata/_xtgeo.py
- tests/test_units/test_ert_context.py
Resolves #1057 
Added a new abstract method `export_to_file` to the `ObjectDataProvider` for exporting the object to file or memory buffer. This method was implemented for each `ObjectDataProvider` subclass by copying the relevant export function from the `_utils.export_file` function.
I was hoping to remove the  `_utils.export_file` function alltogether but it is still needed for the `AggregatedData` class since we can't easily create an `ObjectDataProvider` here as an instance of `ExportData` is needed as argument into the constructor.
Not much tests added, there are quite some tests already on exporting various data types on different format.
> MAINT: Link export functions to each objdata provider

- src/fmu/dataio/_definitions.py
- src/fmu/dataio/providers/objectdata/_xtgeo.py
- tests/test_units/test_ert_context.py
Resolves #1074
Added support for exporting points/polygons as tables on `parquet` format. Necessary for #763 and since we are moving towards `parquet` as standard export format for tables.
> ENH: Add parquet as valid points/polygons format.

- tests/test_schema/test_schemas_up_to_date.py
Fixed test to not fail if komodo release env already exists, meaning if you are in komodo env
> TST: Fix failing test in komodo

- .github/workflows/fmudataio-documention.yml
- docs/src/examples.rst
Resolves #1080 
Update github workflow `fmudataio-documentation.yml` to only build doc and dont deploy:
Readthedocs automatically builds and updates the docs on updates on main, so the `fmudataio-documentation.yml` is now only used for testing that the docs are building with Sphinx. The changes in this PR are made to reflect this and remove outdated code.
> CI: Only build docs, dont deploy

- .github/workflows/ci-fmudataio.yml
- examples/example_metadata/aggregated_surface_depth.yml
- examples/example_metadata/fmu_case.yml
- examples/example_metadata/polygons_field_outline.yml
- examples/example_metadata/polygons_field_region.yml
- examples/example_metadata/preprocessed_surface_depth.yml
- examples/example_metadata/surface_depth.yml
- examples/example_metadata/surface_fluid_contact.yml
- examples/example_metadata/surface_seismic_amplitude.yml
- examples/example_metadata/table_inplace_volumes.yml
- examples/metadata_scripts/post_process_metadata.py
- examples/update_examples.sh
Resolves #1010 
Updated the `post_process_metadata.py` script to insert dummies for some additional fields:
* uuids are replaced with `00000000-0000-0000-0000-000000000000`
* All fields in the `operating_system` block are replaced with dummy values
* `komodo.version` and `fmu-dataio.version` are replaced by dummies.
In this way there will be less noise when the metadata is updated, making it easier to focus on the actual updates.
> DOC: Use dummy for uuids and tracklog props

- examples/example_metadata/fmu_case.yml
- examples/example_metadata/polygons_field_outline.yml
- examples/example_metadata/polygons_field_region.yml
- examples/example_metadata/preprocessed_surface_depth.yml
- examples/example_metadata/surface_depth.yml
- examples/example_metadata/surface_fluid_contact.yml
- examples/example_metadata/surface_seismic_amplitude.yml
- examples/example_metadata/table_inplace_volumes.yml
- schemas/0.9.1/fmu_results.json
- src/fmu/dataio/_models/fmu_results/fmu_results.py
- src/fmu/dataio/_models/fmu_results/specification.py
- src/fmu/dataio/providers/objectdata/_xtgeo.py
- tests/test_units/test_ert_context.py
Resolves #1066 
PR to start adding table specifications to `data.spec` for points and polygons when they are exported on table format: `columns,` `num_columns,` `num_rows` and `size.` 
Points and polygons are mostly exported on table format today. But as long as we support exporting them on `irap_ascii` format, we need to keep all of the added `data.spec` fields as optional. 
This PR comes with a new `FmuResults shcema version 0.9.1`, which updates the relevant examples.
> ENH, SCHEMA: Add table spec for points and polygons

- src/fmu/dataio/providers/objectdata/_base.py
- src/fmu/dataio/providers/objectdata/_provider.py
- tests/test_units/test_objectdataprovider_class.py
Resolves #1086
PR to fix missing `BytesIO` import, it was only included in the `TYPE_CHECKING` imports.
This led to an exception for all objects when they tried to compute the checksum_md5 from memory stream, hence the checksum was computed using the `NamedTemporaryFile` instead.
This should improve the flaky test that was failing, now checksum_md5 will no longer be calculated using temporary files for grid. It is mainly XTGeo cubes that does not support writing to memory stream.
Added a test of the checksum_md5 method directly, that failed prior to the bugfix included here. 
We should enable the ruff rule https://docs.astral.sh/ruff/rules/runtime-import-in-type-checking-block/ to prevent situations like this from going undetected again.
> BUG: Fix missing BytesIO import in ObjectDataProvider

- src/fmu/dataio/case.py
- tests/test_ert_integration/test_wf_create_case_metadata.py
- tests/test_units/test_initialize_case.py
Resolves #997 
Improved warning displayed to user when case metadata already exists on the runpath, with more information on what that actually means to the user and how they can avoid it.
> ENH: Improve case metadata exists warning

- docs/src/standard_results/initial_inplace_volumes.md
- docs/src/standard_results/structure_depth_fault_lines.md
- docs/src/standard_results/structure_depth_surfaces.md
- schemas/file_formats/0.1.0/inplace_volumes.json
- src/fmu/dataio/_models/standard_results/inplace_volumes.py
- src/fmu/dataio/export/rms/__init__.py
- src/fmu/dataio/export/rms/_utils.py
- src/fmu/dataio/export/rms/structure_depth_fault_lines.py
- src/fmu/dataio/export/rms/structure_depth_surfaces.py
- tests/test_export_rms/conftest.py
- tests/test_export_rms/test_export_structure_depth_fault_lines.py
- tests/test_export_rms/test_utils.py
Resolves #763 
PR to add a simple export function for exporting the standard result `structure_depth_fault_lines` from within RMS. Including documentation for how to use the export function. 
Validations include checking that the polygons are closed. I will make a separate PR to include a check that the stratigraphic horizon exists in the `stratigraphy` block in the config, this needs to be added for the existing simple export of the standard result `structure_depth_surfaces` also.
Note the standard result schemas was added in #1083.
> ENH: Add simplified export for structure_depth_fault_lines

- docs/src/standard_results/initial_inplace_volumes.md
- src/fmu/dataio/export/rms/inplace_volumes.py
- tests/test_export_rms/test_export_rms_volumetrics.py
Resolves #1085 
PR to ensure negative values in the computed BULK/PORV column for the water zone are truncated to 0 before validation.
> FIX: Truncate negative bulk/porv values in inplace_volumes

- examples/example_metadata/fmu_case.yml
- examples/example_metadata/polygons_field_outline.yml
- examples/example_metadata/polygons_field_region.yml
- examples/example_metadata/preprocessed_surface_depth.yml
- examples/example_metadata/surface_depth.yml
- examples/example_metadata/surface_fluid_contact.yml
- examples/example_metadata/surface_seismic_amplitude.yml
- examples/example_metadata/table_inplace_volumes.yml
- schemas/0.10.0/fmu_results.json
- src/fmu/dataio/_models/fmu_results/enums.py
- src/fmu/dataio/_models/fmu_results/standard_result.py
Adresses #1047 
Add new standard result `structure_depth_isochore` option to the FmuResults schema `0.10.0` .
Will add test when implementing the simple export function for this standard result.
> SCHEMA: Add new standard result structure_depth_isochore

- docs/src/standard_results/structure_depth_isochores.md
- src/fmu/dataio/_models/fmu_results/fmu_results.py
- src/fmu/dataio/export/rms/__init__.py
- src/fmu/dataio/export/rms/_utils.py
- src/fmu/dataio/export/rms/structure_depth_isochores.py
- tests/test_export_rms/conftest.py
- tests/test_export_rms/test_export_structure_depth_isochores.py
- tests/test_export_rms/test_utils.py
Resolves #1047 
PR to add a new simple export function for the standard result `structure_depth_isochore` to be used to export depth isochore surfaces from within a zones folder in RMS.
> ENH: Add new simple export `export_structure_depth_isochores`

- examples/example_metadata/fmu_case.yml
- examples/example_metadata/polygons_field_outline.yml
- examples/example_metadata/polygons_field_region.yml
- examples/example_metadata/preprocessed_surface_depth.yml
- examples/example_metadata/surface_depth.yml
- examples/example_metadata/surface_fluid_contact.yml
- examples/example_metadata/surface_seismic_amplitude.yml
- examples/example_metadata/table_inplace_volumes.yml
- schemas/0.10.0/fmu_results.json
- schemas/file_formats/0.1.0/field_outline.json
- src/fmu/dataio/_models/__init__.py
- src/fmu/dataio/_models/fmu_results/enums.py
- src/fmu/dataio/_models/fmu_results/standard_result.py
- src/fmu/dataio/_models/standard_results/__init__.py
- src/fmu/dataio/_models/standard_results/field_outline.py
Adresses #765
PR to add a new standard result `field_outline` to the `FmuResult` schema and to add a separate schema for the file format.
- the data type is a `xtgeo.Polygon` and will be stored as a parquet file.
Tests will be added when corresponding simple export function is implemented.
> SCHEMA: Add new standard result 'field_outline'

- docs/src/dataio_3_migration.rst
- examples/example_metadata/fmu_case.yml
- examples/example_metadata/polygons_field_outline.yml
- examples/example_metadata/polygons_field_region.yml
- examples/example_metadata/preprocessed_surface_depth.yml
- examples/example_metadata/surface_depth.yml
- examples/example_metadata/surface_fluid_contact.yml
- examples/example_metadata/surface_seismic_amplitude.yml
- examples/example_metadata/table_inplace_volumes.yml
- schemas/0.10.0/fmu_results.json
- src/fmu/dataio/_models/fmu_results/data.py
- src/fmu/dataio/_models/fmu_results/fmu_results.py
- src/fmu/dataio/providers/objectdata/_export_models.py
- tests/test_units/test_contents.py
Resolves #1102 (which is a "sub-issue" to issue #734)
Added data.property to schema:
Add data.property as optional field for data of content property.
Add data.property.attribute as optional field.
Add data.property.is_discrete as optional field.
> SCHEMA: Add data.property to schema

- src/fmu/dataio/_utils.py
Resolves #1002 
PR to change from importing `roxar` to importing `rmsapi`. 
We no longer support python 3.8 hence this will only be applied to RMS versions >=14.2 where `rmsapi` exists.
Tested running pytest in a rmsvenv, and it works as expected.
> MAINT: Import rmsapi instead of deprecated roxar

- docs/src/standard_results/field_outline.md
- src/fmu/dataio/export/rms/__init__.py
- src/fmu/dataio/export/rms/_utils.py
- src/fmu/dataio/export/rms/field_outline.py
- src/fmu/dataio/export/rms/structure_depth_fault_lines.py
- tests/test_export_rms/test_export_field_outline.py
- tests/test_export_rms/test_utils.py
Resolves #765 
Resolves #304
PR to add a new simple export for the standard result `field_outline`.
This requires a field outline polygon with name `field_outline` at the root of the `General 2D data` folder within RMS.
Note only **one** `field_outline` can be exported per realization. Outlines related to fluid contact outlines should be exported as the planned future standard result `fluid_contact_outline`. Where multiple outlines can be exported, for different fluid contact types and zones. 
Note, only RMS >=14.2 will have access to this export function hence API support for accessing the `General 2D data` folder is in place.
> ENH: Add simple export for standard result 'field_outline'

- schemas/file_formats/0.1.0/structure_depth_fault_lines.json
- src/fmu/dataio/_models/standard_results/structure_depth_fault_lines.py
- src/fmu/dataio/export/_enums.py
- src/fmu/dataio/export/rms/_utils.py
- src/fmu/dataio/export/rms/structure_depth_fault_lines.py
- tests/conftest.py
- tests/test_export_rms/conftest.py
- tests/test_export_rms/test_export_structure_depth_fault_lines.py
- tests/test_export_rms/test_utils.py
Resolves #1118
PR to add fault names to the `structure_depth_fault_lines` standard result table. Possible now after the release of XTGeo 4.7.0 🙂
> ENH: Include fault names in standard result structure_depth_fault_line

- src/fmu/dataio/export/rms/_utils.py
- src/fmu/dataio/export/rms/structure_depth_fault_lines.py
- src/fmu/dataio/export/rms/structure_depth_isochores.py
- src/fmu/dataio/export/rms/structure_depth_surfaces.py
- tests/test_export_rms/test_export_structure_depth_fault_lines.py
- tests/test_export_rms/test_export_structure_depth_isochores.py
- tests/test_export_rms/test_export_structure_depth_surfaces.py
Resolves #1109 
PR to ensure horizons and units exported as standard_result through
- `export_structure_depth_surfaces`
- `export_structure_depth_isochores`
- `export_structure_fault_lines`
have a corresponding entry in the `stratigraphy` block in the global config.
> ENH: Add validation against stratigraphy for relevant simple exports

- examples/example_metadata/fmu_case.yml
- examples/example_metadata/polygons_field_outline.yml
- examples/example_metadata/polygons_field_region.yml
- examples/example_metadata/preprocessed_surface_depth.yml
- examples/example_metadata/surface_depth.yml
- examples/example_metadata/surface_fluid_contact.yml
- examples/example_metadata/surface_seismic_amplitude.yml
- examples/example_metadata/table_inplace_volumes.yml
- examples/metadata_scripts/post_process_metadata.py
- schemas/0.10.0/fmu_results.json
- src/fmu/dataio/_models/fmu_results/fields.py
- src/fmu/dataio/_models/fmu_results/fmu_results.py
- src/fmu/dataio/providers/_fmu.py
- tests/test_schema/test_pydantic_logic.py
- tests/test_units/test_dataio.py
Resolves #1132
Resolves #1134 
PR to start adding `fmu.ensemble` to the `FmuResults` schema and outgoing metadata. The `fmu.iteration` is still kept.
Also added `fmu.ensemble.name` and `fmu.ensemble.uuid` to `CONTRACTUALS`
> SCHEMA: Add fmu.ensemble as duplicate of fmu.iteration

- schemas/0.10.0/fmu_results.json
- src/fmu/dataio/_models/fmu_results/enums.py
- src/fmu/dataio/aggregation.py
- tests/test_units/test_aggregated_surfaces.py
Resolves #1131 
PR to start adding `ensemble` as a valid option for `fmu.context.stage` and to use this value for aggregated data instead of `iteration`
> SCHEMA: Add ensemble as `fmu.context.stage` option

- tests/test_units/test_reader_tsurf.py
Resolves #1141
Used fixture 'tmp_path' to fix potential race condition when unit testing read/write of TSurf files.
- [X ] Tests added (if not, comment why)
- [X ] Test coverage equal or up from main (run pytest with `--cov=src/ --cov-report term-missing`)
- [X ] If not squash merging, every commit passes tests
- [X ] Appropriate [commit prefix](https://upgraded-funicular-eywe4gy.pages.github.io/developing/#commit-prefixes) and precise commit message used
- [X ] All debug prints and unnecessary comments removed
- [X ] Docstrings are correct and updated
- [X ] Documentation is updated, if necessary
- [X ] Latest main rebased/merged into branch
- [X ] Added comments on this PR where appropriate to help reviewers
- [X ] Moved issue status on project board
- [X ] Checked the boxes in this …
> BUG: Fix potential race condition (#1141)

- examples/example_metadata/fmu_case.yml
- examples/example_metadata/polygons_field_outline.yml
- examples/example_metadata/polygons_field_region.yml
- examples/example_metadata/preprocessed_surface_depth.yml
- examples/example_metadata/sumo_ensemble.yml
- examples/example_metadata/sumo_realization.yml
- examples/example_metadata/surface_depth.yml
- examples/example_metadata/surface_fluid_contact.yml
- examples/example_metadata/surface_seismic_amplitude.yml
- examples/example_metadata/table_inplace_volumes.yml
- schemas/0.10.0/fmu_results.json
- src/fmu/dataio/_models/fmu_results/enums.py
- src/fmu/dataio/_models/fmu_results/fields.py
- src/fmu/dataio/_models/fmu_results/fmu_results.py
- tests/test_schema/test_pydantic_logic.py
Resolves #1135 
PR with following additions to the `FmuResultsSchema`
- add `fmu.ensemble` to the `Realization` object, and set `fmu.iteration` to optional. 
- add an `Ensemble` object to the schema with `class=ensemble` (will eventually replace the `Iteration` object)
> SCHEMA: Add Ensemble model, and add fmu.ensemble to Realization object

- src/fmu/dataio/dataio.py
- src/fmu/dataio/providers/objectdata/_xtgeo.py
- tests/test_export_rms/test_export_structure_depth_fault_lines.py
- tests/test_units/test_ert_context.py
Resolves #1146 
PR to enable setting `data.table_index` for points/polygons when they are exported on a tabular format.
> ENH: Enable setting `data.table_index` for points/polygons

- docs/src/standard_results/initial_inplace_volumes.md
- docs/src/standard_results/structure_depth_surfaces.md
- src/fmu/dataio/export/rms/inplace_volumes.py
- src/fmu/dataio/export/rms/structure_depth_fault_lines.py
- src/fmu/dataio/export/rms/structure_depth_surfaces.py
- tests/test_export_rms/test_export_inplace_volumes.py
- tests/test_export_rms/test_export_structure_depth_surfaces.py
Resolves #1144
PR to align the convention for the subfolder for existing simple exports. This should always be set equal to the standard result name.
This should be implemented in the base class once #1101 is addressed.
Existing tests were modified.
> MAINT: Standardise subfolder to be the standard result name

- src/fmu/dataio/providers/_fmu.py
- tests/test_units/test_fmuprovider_class.py
Resolves #1133 
Fully resolves #459 
PR to rename internal variables in the `FmuProvider` from iteration to the ensemble terminology instead. 
To keep the naming convention consistent and prevent confusion in the future.
> MAINT: Rename internal variables from iteration to ensemble

- tests/test_units/test_table.py
Resolves #1087
Fixed issue with the test `test_set_from_exportdata`, which for some occasions when running the tests in distributed mode with `xdist`, fails when trying to unlink paths created under the `tmp_path` pytest fixture directory.
The fix is to remove the unlinking, as `tmp_path` will automatically clean up after the test have been run. As the test was created before `tmp_path` was used, the theory is that the unlinking of the paths is no longer needed.
> TST: Remove path unlinking since path is a tmp_path fixture

- src/fmu/dataio/providers/objectdata/_tables.py
- tests/conftest.py
- tests/test_units/test_contents.py
- tests/test_units/test_table.py
Resolves #1158
PR to fix an too eager warning emitted when comparing the table_index to the standard table_index. 
The warning should only be emitted if required columns are missing or non-standard columns are present.
Also adjusted some tests to have more proper export data to reduce the number of warnings regarding table index when running the tests.
> FIX: Silence overly strict table_index warning

- src/fmu/dataio/_definitions.py
- src/fmu/dataio/providers/objectdata/_base.py
- src/fmu/dataio/providers/objectdata/_faultroom.py
- src/fmu/dataio/providers/objectdata/_provider.py
- src/fmu/dataio/providers/objectdata/_tables.py
- src/fmu/dataio/providers/objectdata/_xtgeo.py
- tests/test_units/test_objectdataprovider_class.py
Resolves #1165
Resolves #1071
PR to remove the `ValidFormats` and set the file `extension` property directly inside each `objectdataprovider` to centralize the logic and to make it more clear what is used as extension.
Also dropped the `hdf` format, it was never possible to export with this format anyway. 
Modified a couple of tests, but existing tests should be sufficient here.
> MAINT: Set file extension in each objdataprovider

- src/fmu/dataio/providers/objectdata/_xtgeo.py
- tests/test_units/test_ert_context.py
The PR #1146 introduced that the table index for polygons is set to an empty list if no table index columns are found. 
This PR sets it to None instead.
> ENH: Set table_index to None instead of empty list for polygons

- src/fmu/dataio/providers/objectdata/_xtgeo.py
- tests/test_units/test_ert_context.py
Use same `table_index` logic for points as for polygons #1172, i.e. set it to `None` if not provided.
> ENH: Set table_index to None instead of empty list for points

- examples/example_metadata/fmu_case.yml
- examples/example_metadata/polygons_field_outline.yml
- examples/example_metadata/polygons_field_region.yml
- examples/example_metadata/preprocessed_surface_depth.yml
- examples/example_metadata/surface_depth.yml
- examples/example_metadata/surface_fluid_contact.yml
- examples/example_metadata/surface_seismic_amplitude.yml
- examples/example_metadata/table_inplace_volumes.yml
- schemas/0.11.0/fmu_results.json
- src/fmu/dataio/_models/fmu_results/enums.py
- src/fmu/dataio/_models/fmu_results/fmu_results.py
- tests/test_units/test_fmuprovider_class.py
Resolves #1052 
PR to remove the `iterative_ensemble_smoother` valid `ert.simulation_mode.` It was removed in Ert 14.
> SCHEMA: Remove iterative_ensemble_smoother as valid ert.simulation_mode

- .github/workflows/ci-fmudataio.yml
- .github/workflows/mypy.yml
- .github/workflows/schemas-up-to-date.yml
- tests/test_units/test_table.py
Resolves #1087 (also for Python 3.8)
Fixed issue with the test `test_set_from_exportdata` which was solved through https://github.com/equinor/fmu-dataio/pull/1159 for the `main` branch, but that also needs to be fixed for the `fmu-dataio` version that still supports `Python 3.8`.
This is simply a cherry-pick of 605e9e1c7a785bbee2255b57e1de6748e9213500
> TST: Remove path unlinking since path is a tmp_path fixture (#1159)

- schemas/0.11.0/fmu_results.json
- src/fmu/dataio/_models/fmu_results/data.py
- src/fmu/dataio/_models/fmu_results/enums.py
Resolves #1125, as part of https://github.com/equinor/fmu-dataio/issues/1108
Added new content: 'fault_triangulated_surface'
> SCHEMA: Add new content type fault_triangulated_surface

- examples/example_metadata/fmu_case.yml
- examples/example_metadata/polygons_field_outline.yml
- examples/example_metadata/polygons_field_region.yml
- examples/example_metadata/preprocessed_surface_depth.yml
- examples/example_metadata/surface_depth.yml
- examples/example_metadata/surface_fluid_contact.yml
- examples/example_metadata/surface_seismic_amplitude.yml
- examples/example_metadata/table_inplace_volumes.yml
- schemas/0.11.0/fmu_results.json
- src/fmu/dataio/_models/fmu_results/fmu_results.py
Resolves #1150 
PR to add `fmu.ert.experiment.id` to the contractuals to make it searchable by elastic search.
> SCHEMA: Add `fmu.ert.experiment.id` to contractuals

- src/fmu/dataio/_metadata.py
- src/fmu/dataio/dataio.py
- src/fmu/dataio/providers/_filedata.py
- tests/test_units/test_filedataprovider_class.py
After #1057 we no longer use the data object inside the `FileDataProvider,` hence the `obj` argument is redundant and is removed in this PR 🧹
Modified some existing tests, new ones not necessary
> MAINT: Remove redundant obj as input argument to FileDataProvider

- examples/example_metadata/fmu_case.yml
- examples/example_metadata/polygons_field_outline.yml
- examples/example_metadata/polygons_field_region.yml
- examples/example_metadata/preprocessed_surface_depth.yml
- examples/example_metadata/sumo_ensemble.yml
- examples/example_metadata/sumo_realization.yml
- examples/example_metadata/surface_depth.yml
- examples/example_metadata/surface_fluid_contact.yml
- examples/example_metadata/surface_seismic_amplitude.yml
- examples/example_metadata/table_inplace_volumes.yml
- schemas/0.11.0/fmu_results.json
- src/fmu/dataio/_models/fmu_results/fields.py
- tests/data/drogon/ertrun1/share/metadata/fmu_case.yml
- tests/data/drogon/ertrun1_no_iter/share/metadata/fmu_case.yml
Resolves #1181
PR to drop the `NaiveDatetime` as type for tracklog events. We always populate them with UTC timezone in outgoing metadata.
> MAINT: Drop NaiveDatetime for tracklog events

- examples/example_metadata/fmu_case.yml
- examples/example_metadata/polygons_field_outline.yml
- examples/example_metadata/polygons_field_region.yml
- examples/example_metadata/preprocessed_surface_depth.yml
- examples/example_metadata/surface_depth.yml
- examples/example_metadata/surface_fluid_contact.yml
- examples/example_metadata/surface_seismic_amplitude.yml
- examples/example_metadata/table_inplace_volumes.yml
- schemas/0.11.0/fmu_results.json
- src/fmu/dataio/_models/fmu_results/fields.py
- src/fmu/dataio/_models/fmu_results/fmu_results.py
- src/fmu/dataio/providers/_filedata.py
- tests/test_units/test_dataio.py
- tests/test_units/test_filedataprovider_class.py
Adresses #644 
PR to start adding a `file.runpath_relative_path` field for data exported in a `realization` context. Data exported in a `case` context will not have this field.
This is the first step towards adding a `fmu.object.identifier` (naming up for discussion) that will be an uuid for identifying objects representing the same thing --> both realization and aggregation representations of a specific object.
> ENH, SCHEMA: Added file.runpath_relative_path field to outgoing metadata

- src/fmu/dataio/types.py
Partially resolves #1126 
Adds the TSurfData class to the inferrable types
> ENH: add TSurfData class to inferrable types (#1126)

- examples/example_metadata/fmu_case.yml
- examples/example_metadata/polygons_field_outline.yml
- examples/example_metadata/polygons_field_region.yml
- examples/example_metadata/preprocessed_surface_depth.yml
- examples/example_metadata/surface_depth.yml
- examples/example_metadata/surface_fluid_contact.yml
- examples/example_metadata/surface_seismic_amplitude.yml
- examples/example_metadata/table_inplace_volumes.yml
- schemas/0.11.0/fmu_results.json
- src/fmu/dataio/_models/fmu_results/enums.py
- src/fmu/dataio/_models/fmu_results/fmu_results.py
- src/fmu/dataio/_models/fmu_results/standard_result.py
Related to #1046 (similar to #1045 for depth domain)
Add a new standard result: `structure_time_surface`. 
Simple export function for exporting time surfaces (from RMS) will be added in a separate PR.
> SCHEMA: add standard result for structure_time_surface

- .github/workflows/ci-fmudataio.yml
- tests/conftest.py
- tests/test_export_rms/test_export_inplace_volumes.py
- tests/test_loaders/test_sumo_interface.py
Resolves #1179 
Github workflow `ci-fmudataio.yml` now fetches a token from Azure to authenticate towards Sumo. This token is set as an environment variables.
The tests in `test_sumo_explorer.py` now reads this token from the environment variables and uses this to set up the connection to Sumo Explorer. 
In addition to this, some more tests were added.
Update 13.05:
@mferrera added a custom fix to handle an issue in the tests caused by a bug in Pyarrow when using the `read_parquet()` function more than once in a pytest module.  Link to bug: https://github.com/apache/arrow/issues/41857
> CI: Fetch sumo explorer token from Azure

- .github/workflows/ci-fmudataio.yml
- ci/testrmsenv.sh
Fixes bug introduced by #1179 
When running the github workflow `ci-fmudataio.yml` from a PR where the source branch does does not belong to the base repo equinor/fmu-dataio, the Authentication step towards Azure will fail as only the github runners in repo equinor/fmu-dataio has been given access to Sumos app reg in Azure.
Now, fetching the Sumo token from Azure and running the tests in `test_sumo_interface.py` are only done when running the workflow from main.
NB! With this change we will also run the tests on push/merge to main
> CI: Only run Azure auth for Sumo from main branch

- src/fmu/dataio/_definitions.py
- src/fmu/dataio/preprocessed.py
- src/fmu/dataio/providers/_filedata.py
- src/fmu/dataio/providers/objectdata/_base.py
- tests/test_units/test_filedataprovider_class.py
Towards #644 
PR to add the export share path as a property on the `ObjectDataProvider.` This export path, and especially the filename, is very connected to attributes of this provider. 
This is a step towards adding an object identifier field in the metadata which should be located in the `fmu` block in the metadata. This identifier will be reliant on this share path, and this PR enables avoiding having to go into the `FileDataProvider` before the `FmuProvider.` 
This PR is mostly a restructuring of existing code, a lot has just been copied from the `FileDataProvider` into a `SharePathConstructor` which is used to set the `share_path` property on the `ObjectDataProvider.`
Added some new tests, but there is significant amount of tests that checks that the exported paths are correct so it …
> MAINT: Make share export location an ObjectDataProvider property

- src/fmu/dataio/_metadata.py
- src/fmu/dataio/dataio.py
- tests/test_units/test_metadata_class.py
PR with some refactoring to avoid initializing the `ObjectDataProvider` more than once per object. 
Essentially this boils down to giving the `ObjectDataProvider` instance as input to the `generate_export_metadata` function instead of the object itself.
> MAINT: Reduce redundant ObjectDataProvider instantiations

- examples/example_metadata/fmu_case.yml
- examples/example_metadata/polygons_field_outline.yml
- examples/example_metadata/polygons_field_region.yml
- examples/example_metadata/preprocessed_surface_depth.yml
- examples/example_metadata/surface_depth.yml
- examples/example_metadata/surface_fluid_contact.yml
- examples/example_metadata/surface_seismic_amplitude.yml
- examples/example_metadata/table_inplace_volumes.yml
- schemas/0.11.0/fmu_results.json
- src/fmu/dataio/_models/fmu_results/fields.py
- src/fmu/dataio/_models/fmu_results/fmu_results.py
- src/fmu/dataio/dataio.py
- src/fmu/dataio/providers/_fmu.py
- tests/test_ert_integration/conftest.py
- tests/test_ert_integration/test_ensemble_experiment_run.py
- tests/test_units/test_aggregated_surfaces.py
- tests/test_units/test_dataio.py
Resolves #644
Relevant issue  https://github.com/equinor/fmu-results-activities/issues/33 
PR to add a `fmu.entity` block to the schema. This block is intended to be used to identify data objects representing the same entity within a case. For now an `uuid` field has been added, and it will be a `UUID` created from the `case_uuid` and the `runpath_relative_path`. This UUID will be the same for all realizations and aggregations of the same object whithin a specific case.
I made the id based on the case and not the ensemble now as we discussed. If anyone has suddenly gotten strong opinions against it, please speak up 😄
> SCHEMA, ENH: Add fmu.entity field to outgoing metadata

- schemas/0.11.0/fmu_results.json
- src/fmu/dataio/_models/fmu_results/enums.py
- src/fmu/dataio/_models/fmu_results/fmu_results.py
- src/fmu/dataio/_models/fmu_results/standard_result.py
Towards #1207 
Add standard_result 'fluid_contact_surface' to the schema. 
A simple export for it will be created in a subsequent PR.
> SCHEMA: Add standard_result 'fluid_contact_surface'

- examples/example_metadata/fmu_case.yml
- examples/example_metadata/polygons_field_outline.yml
- examples/example_metadata/polygons_field_region.yml
- examples/example_metadata/preprocessed_surface_depth.yml
- examples/example_metadata/surface_depth.yml
- examples/example_metadata/surface_fluid_contact.yml
- examples/example_metadata/surface_seismic_amplitude.yml
- examples/example_metadata/table_inplace_volumes.yml
- schemas/0.11.0/fmu_results.json
- src/fmu/dataio/_models/fmu_results/enums.py
- src/fmu/dataio/_models/fmu_results/standard_result.py
- src/fmu/dataio/_models/standard_results/__init__.py
- src/fmu/dataio/_models/standard_results/fluid_contact_outline.py
Towards https://github.com/equinor/fmu-dataio/issues/1208
Add standard_result 'fluid_contact_outline' to the schema.
A simple export for it will be created in a subsequent PR.
> SCHEMA: Add standard_result 'fluid_contact_outline'

- nginx.conf
Resolves #issue
Add option to list schema versions in json format by adding `?json=true` to the request uri.
Related to tasks in Sumo where we want to run our tests using all available schema versions.
- https://github.com/equinor/sumo-canary/issues/210
- https://github.com/equinor/sumo-canary/issues/207
> ENH: option to get schema version list as json

- tests/test_loaders/test_sumo_interface.py
Skipping sumo interface tests while investigating instability issues with the tests, causing them to fail at random occations.
> TST: Skip sumo interface tests

- tests/test_units/test_reader_tsurf.py
Resolves #1212 
Added test for reading TSurf file when its path is a string (and not e.g. a Path)
> TST: add TSurf file read test when path is string (#1212)

- examples/example_metadata/fmu_case.yml
- examples/example_metadata/polygons_field_outline.yml
- examples/example_metadata/polygons_field_region.yml
- examples/example_metadata/preprocessed_surface_depth.yml
- examples/example_metadata/surface_depth.yml
- examples/example_metadata/surface_fluid_contact.yml
- examples/example_metadata/surface_seismic_amplitude.yml
- examples/example_metadata/table_inplace_volumes.yml
- schemas/0.11.0/fmu_results.json
- src/fmu/dataio/_definitions.py
- src/fmu/dataio/_models/fmu_results/enums.py
- src/fmu/dataio/_models/fmu_results/specification.py
- src/fmu/dataio/providers/objectdata/_triangulated_surface.py
Further towards #1126.
Adds TriangulatedSurfaceProvider as a new provider
> ENH, SCHEMA: create triangulated surface provider

- src/fmu/dataio/providers/objectdata/_faultroom.py
- tests/test_units/test_objectdataprovider_class.py
Resolves #1175 
Retrieve `xmax` instead of `xmin` in `FaultRoomSurfaceProvider.get_bbox()`
Added a few tests
> BUG, TST: get xmax instead of xmin in bbox (#1175)

- docs/src/standard_results/fluid_contact_surfaces.md
- src/fmu/dataio/export/rms/__init__.py
- src/fmu/dataio/export/rms/_utils.py
- src/fmu/dataio/export/rms/fluid_contact_surfaces.py
- tests/test_export_rms/conftest.py
- tests/test_export_rms/test_export_fluid_contact_surfaces.py
- tests/test_export_rms/test_utils.py
Resolves #1207 
PR to add a simple export for the `fluid_contact_surface` standard_result.
This simple export requires a folder named `fluid_contact_surfaces` in the root of the `General 2D data` folder in RMS. The export function will automatically look for subfolders with valid fluid contact names (members of the `enum.FluidContactType`) inside this  `fluid_contact_surfaces` folder, and export all surfaces found inside these contact folders.
Functionality to help create these contact surfaces is ongoing and will be added to `fmu-tools`. When in place the documentation will be updated with a link.
> ENH: Add simple_export for 'fluid_contact_surface'

- docs/src/standard_results/fluid_contact_outlines.md
- src/fmu/dataio/export/rms/__init__.py
- src/fmu/dataio/export/rms/_utils.py
- src/fmu/dataio/export/rms/fluid_contact_outlines.py
- tests/test_export_rms/conftest.py
- tests/test_export_rms/test_export_fluid_contact_outlines.py
- tests/test_export_rms/test_utils.py
Resolves #1208 
PR to add a simple export for the `fluid_contact_outline` standard_result.
Identical to the newly merged PR #1207 except for the object type and the standard result name.
This simple export requires a folder named `fluid_contact_outlines` in the root of the `General 2D data` folder in RMS. The export function will automatically look for subfolders with valid fluid contact names (members of the `enum.FluidContactType)` inside this `fluid_contact_outlines` folder, and export all polygon outlines found inside these contact folders.
Functionality to help create these contact surfaces is ongoing and will be added to `fmu-tools.` When in place the documentation will be updated with a link.
> ENH: Add simple_export for 'fluid_contact_outline'

- src/fmu/dataio/providers/objectdata/_provider.py
- tests/test_units/test_objectdataprovider_class.py
Resolves #1127 
Returns TriangulatedSurfaceProvider from the object data provider factory.
Added testing of the TriangulatedSurfaceProvider and its specification.
> ENH: return TriangulatedSurfaceProvider from provider factory

- .github/workflows/ci-fmudataio.yml
- ci/testrmsenv.sh
- src/fmu/dataio/external_interfaces/schema_validation_interface.py
- src/fmu/dataio/external_interfaces/sumo_explorer_interface.py
- src/fmu/dataio/load/load_standard_results.py
- tests/test_loaders/test_schema_validation_interface.py
- tests/test_loaders/test_standard_result_loaders.py
- tests/test_loaders/test_sumo_interface.py
Resolves #1177 
Added a data class layer to the simple loaders framework. In this way, we have a way to group standard result loaders that share fmu data class (table, polygon, surface etc.) The loader methods that requires custom handling, depending on the data type, can be implemented in this layer. The following data class layers have been added so far:
* `TabularStandardResultsLoader` to handle standard results containing tabular data/tables.
* `PolygonStandardResultLoader` to handle standard results containing polygons.
* `SurfacesStandardResultLoader` handle standard results containing surfaces.
The loader method `save_realization()` has been implemented for each of the data class layers as it requires custom handling for each of the data types. The other loader methods …
> ENH: Add data class layer to simple loaders

- tests/test_loaders/test_schema_validation_interface.py
Resolves #1242 
Skip tests if the schema url in the metadata examples does not exist. 
This will only happen for PR's bumping a schema version.
Tested that it worked locally for #1240
> TST: Fix failing tests when schema is bumped

- src/fmu/dataio/_definitions.py
- src/fmu/dataio/_utils.py
- src/fmu/dataio/dataio.py
- tests/conftest.py
- tests/test_export_rms/test_export_field_outline.py
- tests/test_export_rms/test_export_fluid_contact_outlines.py
- tests/test_export_rms/test_export_fluid_contact_surfaces.py
- tests/test_export_rms/test_export_inplace_volumes.py
- tests/test_export_rms/test_export_structure_depth_fault_lines.py
- tests/test_export_rms/test_export_structure_depth_isochores.py
- tests/test_export_rms/test_export_structure_depth_surfaces.py
- tests/test_units/test_dataio.py
- tests/test_units/test_objectdataprovider_class.py
- tests/test_units/test_prerealization_surfaces.py
- tests/test_units/test_rms_context.py
- tests/test_units/test_utils.py
- tests/utils.py
Resolves #1246 
PR to start using the `RUNRMS_EXEC_MODE` to determine if we are inside the RMS GUI.
This will enable us to remove the `skip_inside_rmsvenv` pytest.mark #1007 which will be adressed in a separate PR
> MAINT: Use RUNRMS_EXEC_MODE to determine if inside RMS

- ci/testrmsenv.sh
- pyproject.toml
- src/fmu/dataio/export/rms/inplace_volumes.py
- tests/test_units/test_dataio.py
- tests/test_units/test_filedataprovider_class.py
- tests/test_units/test_fmuprovider_class.py
- tests/test_units/test_table.py
- tests/test_units/test_utils.py
Resolves #1007 
PR to remove the `skip_inside_rmsvenv` `pytest.mark`. 
We no longer need to skip any tests when we have moved away from checking if `rmsapi` is available, and instead use the environment variable from `runrms` to determine if we are inside RMS or not #1246 
Note I did test to run the tests locally inside a `rmsvenv` and with these changes the tests run fine both inside and outside.
> TST: Remove skip_inside_rmsvenv mark

- docs/src/standard_results/structure_time_surfaces.md
- src/fmu/dataio/export/rms/__init__.py
- src/fmu/dataio/export/rms/structure_time_surfaces.py
- tests/test_export_rms/test_export_structure_time_surfaces.py
Addresses #issue1046
Add a simple export function for exporting the standard result `structure_time_surface` from within RMS. Including Documentation for how to use the export function.
> ENH: Add simple export for structure_time_surfaces

- src/fmu/dataio/_metadata.py
- src/fmu/dataio/_models/fmu_results/enums.py
- src/fmu/dataio/_models/fmu_results/fmu_results.py
- src/fmu/dataio/external_interfaces/sumo_explorer_interface.py
- src/fmu/dataio/load/load_standard_results.py
- src/fmu/dataio/providers/objectdata/_base.py
- src/fmu/dataio/providers/objectdata/_faultroom.py
- src/fmu/dataio/providers/objectdata/_provider.py
- src/fmu/dataio/providers/objectdata/_tables.py
- src/fmu/dataio/providers/objectdata/_triangulated_surface.py
- src/fmu/dataio/providers/objectdata/_xtgeo.py
- tests/test_loaders/test_sumo_interface.py
Addresses #1148 
The enum `FMUClass` in `fmu_results` is split in two separate classes of metadata for a) data objects (often originating from RMS) and for b) results from FMU.
Moreover, most of the enums are now based on StrEnum rather than (str, Enum). But two of the enums were not straight-forward to update.
A replacement of the literal in the schema revealed challenges that are not addressed in this PR. Hence the enum for object metadata is still taken as literal when added into the object metadata schema.
> ENH: split fmu class

- docs/src/standard_results/fluid_contact_outlines.md
- docs/src/standard_results/fluid_contact_surfaces.md
- docs/src/standard_results/structure_depth_fault_lines.md
- docs/src/standard_results/structure_depth_isochores.md
- src/fmu/dataio/external_interfaces/sumo_explorer_interface.py
- src/fmu/dataio/load/load_standard_results.py
- tests/test_loaders/test_standard_result_loaders.py
- tests/test_loaders/test_sumo_interface.py
Resolves #1244 
Added simple loader interface for the `fluid_contact_surfaces` standard result. This covers:
* A new loader function `load_fluid_contact_surfaces()`
* A new loader object `FluidContactSurfacesLoader`
* Better naming of the data objects returned to the user to ensure uniqueness
* Added and adjusted tests
* Added documentation for fluid contact surfaces
Added a few comments and questions for discussion.
> ENH: Simple loader for fluid contact surfaces

- ci/testrmsenv.sh
Resolves #1261 
Updated the `testrmsenv.sh` script to force update the pip package `pytest` before running the `fmu-dataio` tests. This script is used when testing the RMS envs.
This update was needed as some of the tests in `fmu-dataio` does not work with the pytest version that comes with the RMS env.
> CI: Force update pytest in rmsenv test script

- src/fmu/dataio/_models/fmu_results/enums.py
Resolves #1227 
Added 'structure_depth_fault_triangulated_surface' to standard results enum
> ENH: add structure_depth_fault_triangulated_surface to standard results enum (#1227)

- docs/src/dataio_3_migration.rst
- src/fmu/dataio/providers/objectdata/_tables.py
- src/fmu/dataio/providers/objectdata/_utils.py
- tests/test_units/test_dataio.py
- tests/test_units/test_filedataprovider_class.py
- tests/test_units/test_table.py
Resolves #1263 
PR to start dropping empty columns from the `data.table_index` and to add a deprecation notice saying it will not be allowed in the future. A `table_index` column should only contain valid values and not be empty.
> ENH, DEP: Drop empty columns from table_index

- src/fmu/dataio/_utils.py
- src/fmu/dataio/aggregation.py
- src/fmu/dataio/providers/_filedata.py
- src/fmu/dataio/providers/objectdata/_base.py
- tests/test_units/test_objectdataprovider_class.py
Resolves #1061
PR to start re-adding `file.size_bytes` into the metadata again. 
This is listed as a contractual field and is information that is nice to know.
> ENH: Re-populate file.size_bytes

- src/fmu/dataio/_metadata.py
- src/fmu/dataio/_models/fmu_results/fmu_results.py
- src/fmu/dataio/_runcontext.py
- src/fmu/dataio/case.py
- src/fmu/dataio/providers/_fmu.py
- tests/test_units/test_fmuprovider_class.py
- tests/test_units/test_initialize_case.py
- tests/test_units/test_run_context.py
Resolves #1278
🧹 Drop redundant `CaseMetadataExport` model and use the  `CaseMetadata` instead
> MAINT: Drop redundant CaseMetadataExport

- .github/workflows/ci-fmudataio.yml
- .github/workflows/mypy.yml
- ci/testrmsenv.sh
- src/fmu/dataio/_models/fmu_results/global_configuration.py
Resolves #990 
We no longer support `python` versions older than `3.11.` Hence this custom `pydantic` handling can be removed.
> CI: Drop custom pydantic handling

- examples/example_metadata/fmu_case.yml
- examples/example_metadata/polygons_field_outline.yml
- examples/example_metadata/polygons_field_region.yml
- examples/example_metadata/preprocessed_surface_depth.yml
- examples/example_metadata/surface_depth.yml
- examples/example_metadata/surface_fluid_contact.yml
- examples/example_metadata/surface_seismic_amplitude.yml
- examples/example_metadata/table_inplace_volumes.yml
- examples/metadata_scripts/post_process_metadata.py
- schemas/0.13.0/fmu_results.json
- src/fmu/dataio/_models/fmu_results/fmu_results.py
Resolves sub-task in the release manager duties
Bumping fmu_results schema to version `0.13.0` now that a new version of fmu-dataio has just been released.
> SCHEMA: Bump fmu_results to 0.13.0

- examples/example_metadata/aggregated_surface_depth.yml
- examples/example_metadata/fmu_case.yml
- examples/example_metadata/polygons_field_outline.yml
- examples/example_metadata/polygons_field_region.yml
- examples/example_metadata/preprocessed_surface_depth.yml
- examples/example_metadata/surface_depth.yml
- examples/example_metadata/surface_fluid_contact.yml
- examples/example_metadata/surface_seismic_amplitude.yml
- examples/example_metadata/table_inplace_volumes.yml
- examples/metadata_scripts/post_process_metadata.py
Resolves #1283 
PR to make future schema change PR's a bit less verbose and reduce merge conflicts, by setting the `datetime` in the tracklog to the` unix epoch`.
Also hardcoded the `fmu.entity.uuid` like the other uuid's
> ENH: Set datetime in examples to unix epoch

- src/fmu/dataio/export/rms/_utils.py
- tests/test_export_rms/test_utils.py
Resolves #1202
PR to add a check of the RMS object type before initializing them with xtgeo. This prevents cryptic errors coming from the `rmsapi` from reaching the user. Ideally xtgeo should give a more user friendly error here. @jcrivenaes I'll make an issue 👍 .
> ENH: Add check of rms object type

- examples/example_metadata/geogrid--facies.yml
- examples/example_metadata/geogrid--phit.yml
- examples/example_metadata/geogrid.yml
- examples/update_examples.sh
Resolves #1289 
PR to add grid and some grid property metadata to the example_metadata folder.
> ENH: Add grid and grid property metadata to examples

- examples/example_metadata/fmu_case.yml
- examples/example_metadata/geogrid--facies.yml
- examples/example_metadata/geogrid--phit.yml
- examples/example_metadata/geogrid.yml
- examples/example_metadata/polygons_field_outline.yml
- examples/example_metadata/polygons_field_region.yml
- examples/example_metadata/preprocessed_surface_depth.yml
- examples/example_metadata/surface_depth.yml
- examples/example_metadata/surface_fluid_contact.yml
- examples/example_metadata/surface_seismic_amplitude.yml
- examples/example_metadata/table_inplace_volumes.yml
- schemas/0.13.0/fmu_results.json
- src/fmu/dataio/_models/fmu_results/data.py
- src/fmu/dataio/_models/fmu_results/enums.py
- src/fmu/dataio/_models/fmu_results/fmu_results.py
- tests/test_units/test_contents.py
Resolves #1293 
Renamed the item 'fault_triangulated_surface' in the Content enum to 'fault_surface' so that it aligns better with the general pattern in the other Contents
> FIX, SCHEMA: rename content enum and update schema (#1293)

- src/fmu/dataio/external_interfaces/sumo_explorer_interface.py
- tests/test_loaders/test_sumo_interface.py
Resolves #1302
Point simple loaders to Sumo prod unless simple loader is run from a "Komodo bleeding" environment.
Now that the simple loaders have been released through Komodo, the integration towards Sumo should be updated to point to Sumo prod. This switch will be released in Komodo through the Komodo 2025.08 release. The simple loaders will keep pointing to dev from "bleeding" Komodo environments.
> REL: Point simple loaders to Sumo prod

- src/fmu/dataio/load/load_standard_results.py
- tests/test_loaders/test_standard_result_loaders.py
Resolves #1308 
The simple loader input parameter `case_id` is now a str. This change was made by request from FMU User @richypitman through #1308
> ENH: Make simple loader input case_id a str

- src/fmu/dataio/scripts/create_case_metadata.py
- tests/test_ert_integration/conftest.py
- tests/test_ert_integration/test_simple_export_run.py
Resolves #1329 
PR that fixes a bug where the user is told to remove the `ert_username` argument from the `WF_CREATE_CASE_METADATA`, but doing so triggers a failure since the argument is still required.
> BUG: Make 'ert_username' actually optional

- src/fmu/dataio/preprocessed.py
See issue #https://github.com/equinor/fmu-datamodels/issues/69 and PR #https://github.com/equinor/fmu-datamodels/pull/70.
Adapted `fmu-dataio` to small change in `fmu-datamodels.TrackLog` class API.
> MAINT: adapt to cleanup in fmu-datamodels.TrackLog
